### PR TITLE
Impl BodyEncoding for Response

### PR DESCRIPTION
**Pull request by DoumanAsh**
Would be nice to have it as it was originally in 0.7 for `HttpResponse`

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you add test

**Comment by fafhrd91** [comment]
https://github.com/actix/actix-web/blob/master/tests/test_server.rs#L87

**Comment by DoumanAsh** [comment]
Yeah sure, give me a sec

**Comment by DoumanAsh** [comment]
Added

**Review by fafhrd91 — APPROVED** [review]

**Pull request merged**
