### PR TITLE
added more http method functions to TestRequest

### PR DESCRIPTION
**Pull request by Dowwie**

### CODE REVIEW

**Review by fafhrd91 — CHANGES_REQUESTED** [review]
Please add tests as well

**Comment by otavio** [comment]
It also lacks the docstrings.

**Comment by Dowwie** [comment]
> It also lacks the docstrings.

wallflower?

**Comment by fafhrd91** [comment]
@Dowwie you should add doc strings as well

**Review by fafhrd91 — CHANGES_REQUESTED** [review]
tests and doc strings

**Pull request closed without merging**
