### PR TITLE
Replace sha1 dependency with sha-1

### PR DESCRIPTION
**Pull request by linkmauve**
This other crate is being maintained, and it offers better performances when using the `asm` feature (especially [on AArch64](https://github.com/RustCrypto/hashes/pull/97)).

### CODE REVIEW

**Review by JohnTitor — DISMISSED** [review]
Could you also update CHANGES.md?

**Comment by linkmauve** [comment]
Done.

**Comment by JohnTitor** [comment]
Sorry again, could you rebase to make CI green?

**Comment by JohnTitor** [comment]
Ah, could you add a unit test to confirm that the output isn't changed?

like:

```rust
#[test]
fn test_hash_key() {
    let foo = hash_key("hello actix-web".as_bytes());
    assert_eq!(&foo, "cR1dlyUUJKp0s/Bel25u5TgvC3E=");
}
```

**Comment by linkmauve** [comment]
Done.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
