### PR TITLE
Add unix domain socket example

### PR DESCRIPTION
**Pull request by messense**
Ref #92 

```bash
$ curl --unix-socket /tmp/actix-uds.socket http://localhost/
Hello world!
```

### CODE REVIEW

**Comment by messense** [comment]
Although this will only one thread for handling incoming connections according to the [documentation](https://actix.github.io/actix-web/actix_web/struct.HttpServer.html#method.start_incoming).

And it does not delete the socket file (`/tmp/actix-uds.socket`) when stopping the server so it will fail to start next time you run it unless you delete the socket file manually.

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
I thought you want to add something like `.bind_uds` or something like that

**Comment by messense** [comment]
Yes, I still want that. But getting a working example of current code will help me iterate the API design and will be much clear when reviewing that PR someday.

**Comment by fafhrd91** [comment]
Sounds good

**Pull request merged**
