### PR TITLE
Private serde fork

### LINKED ISSUE #371: serde query extractor fails on simple enum types
It seems that something in how the contents of a query string are passed to serde is causing breakage with simple enum types.

For the enum

```rust
// #[serde(untagged)]
// #[serde(rename_all = "camelCase")]
#[derive(Deserialize)]
pub enum ResponseType {
    Token,
    Code
}

#[derive(Deserialize)]
pub struct AuthRequest {
    client_id: String,
    redirect_uri: String,
    response_type: ResponseType,
    scope: String,
}
```

and with the handler

```rust
fn authorize(params: Query<AuthRequest>) -> impl Responder {
    format!("Do you authorize this application to sync files on your behalf?")
}
```

a request to `/authorize?...&response_type=code` (or `Code` or `ResponseType::Code` or `1` or any of a dozen other permutations I tried) I get back an error along the lines of the following:

```
 DEBUG actix_web::pipeline    > Error { err: "invalid type: string \"code\", expected enum ResponseType" }


 INFO  actix_web::middleware::logger > 127.0.0.1:52722 [06/Jul/2018:22:54:00 -0500] "GET /authorize?client_id=ebb82a88-8197-11e8-85a6-fb14d7e72e94&redirect_uri=msn.com&response_type=code HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 0.000427
```

As you can see from the commented-out code, I also tried playing around with different serde enum representations and formatting options.

### PR DESCRIPTION
**Pull request by DoumanAsh**
Closes #371

@Dowwie @mqudsi

### CODE REVIEW

**Comment by fafhrd91** [comment]
we can not publish crate if it contain local dependency

**Comment by DoumanAsh** [comment]
@fafhrd91 Oh is that so? Then should I make it part of workspace?

**Comment by fafhrd91** [comment]
all dependencies have to be released on crates.io
workspace won't help. it should part of actix-web crate or we have to publish new crate, I'd prefer first

**Comment by DoumanAsh** [comment]
Ok, got you, I hoped to separate urlencoded so that we could easily swap it out, but I guess there is no choice

**Comment by DoumanAsh** [comment]
serde_urlencoded moved into repo, I retained its test to not lower our coverage too much, well at least I hope

**Review by fafhrd91 — APPROVED** [review]

**Pull request merged**
