### PR TITLE
Fix preflight CORS header compliance; refactor previous patch

### LINKED ISSUE #716: Only return a single origin value in preflight
Following [this issue](https://github.com/actix/actix-web/issues/603) having been merged and closed, I thought it would fix my issue. However, Chrome, Firefox, and Safari all still complain about multiple values in the `ACCESS_CONTROL_ALLOW_ORIGIN` header in CORS preflight (i.e.: when responding to the `OPTIONS` command). Since this is handled in the `Middleware::start` method, with was not updated by the previous patch, and I'd like to fix both responses and refactor to remove duplication.

Take a look at [this gist](https://gist.github.com/dmcguire81/f3f459a0a5a570ca1482d596ba36460a) for the repro case that I've been using to test the implementation, since I'm hoping to consume an actix-powered REST API both via our website, and via interactive Swagger UI documents hosted separately (hence the two origins).

### Browser

The specific CORS restriction I'm working around looks like this, in Chrome:

```
Access to fetch at 'http://localhost:8088/' from origin 'http://localhost:5200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'http://localhost, http://localhost:5200', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Wire

Over-the-wire, the failed interaction looks like this:

```
OPTIONS / HTTP/1.1
Host: localhost:8088
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:5200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
Referer: http://localhost:5200/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

HTTP/1.1 200 OK
access-control-allow-headers: content-type
access-control-allow-origin: http://localhost, http://localhost:5200
access-control-allow-methods: GET,OPTIONS,PATCH,DELETE,HEAD,PUT,POST
content-length: 0
date: Wed, 06 Mar 2019 23:51:49 GMT
```

### Wire

When corrected, the wire protocol finished correctly (and the Chrome Dev Tools console is silent):

```
OPTIONS / HTTP/1.1
Host: localhost:8088
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://localhost:5200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Access-Control-Request-Headers: content-type
Accept: */*
Referer: http://localhost:5200/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

HTTP/1.1 200 OK
access-control-allow-headers: content-type
access-control-allow-origin: http://localhost:5200
access-control-allow-methods: PUT,POST,PATCH,DELETE,OPTIONS,GET,HEAD
content-length: 0
date: Wed, 06 Mar 2019 23:50:06 GMT

POST / HTTP/1.1
Host: localhost:8088
Connection: keep-alive
Content-Length: 17
accept: application/text
Origin: http://localhost:5200
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Content-Type: application/text
Referer: http://localhost:5200/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

Hello actix-web!
HTTP/1.1 200 OK
content-length: 12
content-type: text/plain; charset=utf-8
access-control-allow-origin: http://localhost:5200
vary: Origin
date: Wed, 06 Mar 2019 23:50:06 GMT

Hello world!
```

### PR DESCRIPTION
**Pull request by dmcguire81**
Fixes #716

### CODE REVIEW

**Comment by dmcguire81** [comment]
@acycliczebra want to take a look and see if this is consistent with your original intent - seems the same constraints apply to the CORS preflight.

**Review by DoumanAsh — APPROVED** [review]
Oh this is good, you refactored it into common routine

Thank you, could you please add the note about this fix to  CHANGELOG.md?

**Comment by DoumanAsh** [comment]
@fafhrd91 Did 1.0.0 take CORS middleware as it is from master? Maybe we would need to port these changes to 1.0 branch

**Comment by fafhrd91** [comment]
We can port it later. I am planing to switch default branch in 2 weeks

**Comment by dmcguire81** [comment]
@DoumanAsh Updated `CHANGES.md`.

**Comment by DoumanAsh** [comment]
Thanks
I'll wait for @acycliczebra to input some comments on this weekend, and then will merge it

**Comment by acycliczebra** [comment]
Yeah this looks good to me. LGTM!

**Comment by dmcguire81** [comment]
@DoumanAsh @fafhrd91 I didn't quite follow the discussion on porting to the branch 1.0 - can you point me at a roadmap so I know the relevant release to look for?

**Comment by fafhrd91** [comment]
@dmcguire81 check 1.0 branch. there is no specific roadmap, we just port all functionality to 1.0

you are welcome to help if you'd like. i think cors middleware should easier to use on 1.0, because of design changes.

**Pull request merged**
