### PR TITLE
add msrv to clippy config

### LINKED ISSUE #1861: add msrv to clippy config
https://github.com/rust-lang/rust-clippy#specifying-the-minimum-supported-rust-version

### PR DESCRIPTION
**Pull request by ibraheemdev**
ref  #1861

### CODE REVIEW

**Comment by ibraheemdev** [comment]
Oh, I totally missed that `custom_inner_attributes` is unstable. Should I create a `clippy.toml` instead?

**Comment by robjtede** [comment]
Yeah let's put it in a chippy config file. I assumed we had one already.

**Comment by robjtede** [comment]
appears that this new feature isn't supported in the distributed clippy version yet

**Comment by robjtede** [comment]
Ahh right, it's still attr based.

**Comment by ibraheemdev** [comment]
Is this feature available now?

**Review by robjtede — APPROVED** [review]
nice, thanks

**Pull request merged**
