### PR TITLE
doc fix

### PR DESCRIPTION
**Pull request by lzxZz**
the file "src/httpresponse.rs" have a comment error in line 275

### CODE REVIEW

**Comment by DoumanAsh** [comment]
Thanks

**Comment by lzxZz** [comment]
the web page https://actix.rs/api/actix-web/stable/actix_web/struct.HttpResponse.html remain this mistake. I commit a pull request

**Comment by DoumanAsh** [comment]
This is for stable version of documentation, which will get updated with new crates.io release

**Comment by lzxZz** [comment]
ok

**Pull request merged**
