### PR TITLE
files: inline disposition for common web app file types

### LINKED ISSUE #610: Javascript Files Content-Disposition Incorrectly Detected as Attachement
Current the mime detection from mime_guess correctly identifies javascript files as "application/javascript" but that doesn't match any of the specially named Mime types `mime::IMAGE`, `mime::TEXT`, or `mime::VIDEO` which is currently marked as inline.

This can be worked around through the StaticFileConfig, but the default for these files should be correct for a webserver.

### PR DESCRIPTION
**Pull request by aliemjay**
## PR Type

Bug fix

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

Closes #610

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
LGTM! Could you also add a changelog entry?

**Review by ekrem95 — APPROVED** [review]

**Comment by robjtede** [comment]
Are there other mime types that should be considered here?

Ones that come to mind:
- application/javascript (utf8 variant)
- application/wasm
- application/json
- application/x-www-form-urlencoded

**Comment by aliemjay** [comment]
>     * application/javascript (utf8 variant)
already covered

>     * application/wasm
>     * application/json
sure!

>     * application/x-www-form-urlencoded
This doesn't occur in static files. right?

**Comment by robjtede** [comment]
utf8 => right, `.subtype` doesn't care about parameters
urlencoded => true, leave it out

**Comment by aliemjay** [comment]
How about?:

audio/*
application/graphql
application/xml

**Comment by aliemjay** [comment]
On the other side, I don;t want this to be bloated. The user can easily override the defaults.

**Comment by robjtede** [comment]
We'd like to have sensible defaults for common web activities where static files are used. I think WASM and JSON make sense in addition to javascript but the others mentioned are a stretch, as you say other use cases can be supported with custom configs.

**Review by robjtede — APPROVED** [review]

**Pull request merged**
