### PR TITLE
remove generic type B for app::App

### PR DESCRIPTION
**Pull request by fakeshadow**
## PR Type

Refactor

## PR Checklist
Check your PR fulfills the following:

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

This generic type is unnecessary as type `B` is constraint by `T` so we can leave it out of `App`.
Not big improvement as the major block for easy binding/returning `App` is the type `T` but with this PR if no middleware and/or middleware function is warpped it would be pretty easy to bind the `App`.

### CODE REVIEW

**Review by popzxc — APPROVED** [review]

**Review by JohnTitor — APPROVED** [review]
Looks reasonable to me!

**Comment by robjtede** [comment]
Is this breaking?

**Comment by JohnTitor** [comment]
> 
> 
> Is this breaking?

This removes the private field of `App` and loosens bounds so these changes should be semver-minor, right?

**Comment by fakeshadow** [comment]
This could be a break change if people managed to return an `App` from a function call somehow. They would have to remove the second type signature of `App`.

**Comment by Neopallium** [comment]
How about leaving `B` on `App`, but not using it internally?  Schedule it for removal in 3.1.x?

**Comment by robjtede** [comment]
Does this provide any tangible improvements? We'd need a very good reason to break semver despite the low number of projects that would be affected.

**Comment by fakeshadow** [comment]
The type signautre of returning an `App` would change from
```
App<impl ServiceFactory<..B>, B>
```
to
```
App<impl ServiceFactory<..B>>
```

And it can be simplified to `App<AppEntry>` if no `wrap` and `warp_fn` is used on it.
So no it's not a big improvement.

**Comment by fakeshadow** [comment]
I just found out all the middle types of `Appxx` can be simplied a litte as well. So this pr needs some more work.

**Comment by fakeshadow** [comment]
`App` and it's middle types now is completely not bound to `B`. The break comes from with two parts: 
1. middlewares (Logger, Compress) used to return a wrapper type as `ServiceResponse<Wrapper<B>>`. This is now changed to return `ServiceRequest<B>` directly. The wrapper types are transformed to it in place with:
```rust
Response::Other(Body::Message(Box<dyn MessageBody + Unpin>))
```

2. return an `App` from function can be simplied to `App` or
```rust
App<impl ServiceFactory<
        Config = (),
        Request = ServiceRequest,
        Response = ServiceResponse,
        Error = Error,
        InitError = (),
    >>
```

**Comment by fakeshadow** [comment]
I think this PR can be closed for now.

I didn't think through before making the changes. Wrapping the stream type returned in a Boxed trait object could be hurting performance noticeably when there are multiple middleware used that would alter the output payload stream.

I would give it another try where the B type is not boxed.

**Pull request closed without merging**
