### PR TITLE
Add Content-Disposition to NamedFile (fixes #172)

### LINKED ISSUE #172: Add Contet-Disposition header support to NamedFile
At the moment responder implementation does not add content-disposition header to a NamedFile response

### PR DESCRIPTION
**Pull request by svenstaro**
I used the raw strings for the headers instead of stuff in `content_disposition.rs` because that is commented out and I don't know why that is.

### CODE REVIEW

**Comment by DoumanAsh** [comment]
Hej @svenstaro in past we had some talk about this header with @fafhrd91 
Sadly I was a bit busy to work on it myself, but we had idea about simple heuristic to deterine whether file should be inline or attachment.
Things like images should more like to be as `inline` rather than attachment.

And more importantly it would be nice to have a way for user to configure it in place of automatic settings my actix-web itself.

**Comment by svenstaro** [comment]
Alright fair enough but for now this would be an improvement over the current state for sure.

**Comment by fafhrd91** [comment]
@svenstaro could you use inline for images and text

you can check mimetype by `get_mime_type(&ext.to_string_lossy(())`

**Review by fafhrd91 — CHANGES_REQUESTED** [review]
could you use inline for images and text. you can check mimetype by get_mime_type(&ext.to_string_lossy(())

**Comment by svenstaro** [comment]
@fafhrd91 fixed with tests.

**Comment by fafhrd91** [comment]
thanks

**Pull request merged**
