### PR TITLE
update to router 0.5.0 beta

### PR DESCRIPTION
**Pull request by robjtede**
## PR Type

Refactor

## PR Checklist

- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview
Move router crate here and update web accordingly.

### CODE REVIEW

**Comment by aliemjay** [comment]
While revisiting #2295,  I've just found a breaking change with the new router.

The previous behavior...

```rust
// matches "/hello"
scope("/").service(scope("/").route("/hello", ...))

// matches "/a/b/c"
scope("/a/").service(scope("/b/").route("/c", ...))

// inconsistency with dynamic prefixes; matches "/a//b//c"
scope("/{a}/").service(scope("/{b}/").route("/{c}", ...))
```

People are using `scope("/")` instead of `sope("")`.

We need to either preserve the old behavior and have some magic in web to strip trailing slash from (non-dynamic) prefixes, or enforce the new and what I think the more correct behavior.

**Comment by robjtede** [comment]
@aliemjay would appreciate a sanity check especially in rmap.rs

**Review by aliemjay — APPROVED** [review]
LGTM

**Comment by aliemjay** [comment]
I think this change should be mentioned in the migration guide.

> ```rust
> // matches "/hello"
> scope("/").service(scope("/").route("/hello", ...))
> 
> // matches "/a/b/c"
> scope("/a/").service(scope("/b/").route("/c", ...))
> 
> // inconsistency with dynamic prefixes; matches "/a//b//c"
> scope("/{a}/").service(scope("/{b}/").route("/{c}", ...))
> ```

**Pull request merged**
