### PR TITLE
replace askama_escape in favor of v_htmlescape

### PR DESCRIPTION
**Pull request by zzau13**
## Feature
n the new version, v_htmlescape@0.15, it has no dependencies and is a generated file of about 1500 lines of code. Compile time is minimal and it is optimized with simd instructions on x86 and x86_64. 

Sorry for taking so long.

## PR Checklist
- [x] ~~Tests for the changes have been added / updated.~~
- [x] ~~Documentation comments have been added / updated.~~
- [x] ~~A changelog entry has been made for the appropriate packages.~~
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

Previous PR: https://github.com/actix/actix-web/pull/2402

### CODE REVIEW

**Comment by cetra3** [comment]
Lots of [`unsafe` in this lib](https://github.com/botika/v_escape/search?q=unsafe), while there is none I could see in askama. 

Is there any benefit here besides less dependencies?  Is it faster to use?

**Comment by robjtede** [comment]
I'm assuming the unsafe is largely to do with running SSE/AVX code.

**Comment by zzau13** [comment]
If necessary I can put more test coverage. And I have had the fuzzy tests for hours without failures. Anything you need, say it and I'll implement it.

**Comment by zzau13** [comment]
@cetra3 https://github.com/rust-lang/rust/search?q=unsafe 

Is there a problem that needs to be fixed? This library was already used before in actix for a long time and has not given any problem. And of course it is many times faster than anyone. I invite you to look at the benchmarks.

**Review by robjtede — APPROVED** [review]

**Pull request merged**
