### PR TITLE
pretty printing internal server error

### PR DESCRIPTION
**Pull request by DominicWrege**
## PR Type

Update

## PR Checklist
Check your PR fulfills the following:

- [ ] Tests for the changes have been added / updated.
- [ ] Documentation comments have been added / updated.
- [ ] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview

Internal server errors would be more readable

### CODE REVIEW

**Review by otavio — COMMENTED** [review]
I have mixed feelings about this. This will increase the reading of the error for sure, but I also think some people don't want this as it becomes harder to process as it becomes a multi-line error.

Maybe we could have a type to let the user choose if he/she wants the `PrettyPrintError` or not?

**Comment by DominicWrege** [comment]
I do not see any benefits in an error which its unreadable. Currently the user has no option either but maybe we can find a good way between?!

**Comment by otavio** [comment]
> I do not see any benefits in an error which its unreadable. Currently the user has no option either but maybe we can find a good way between?!

As said, it is more readable but I am unsure all users will prefer it as you are proposing. Maybe @robjtede or @fakeshadow can share their view on this?

**Comment by DominicWrege** [comment]
Yeah good point. Maybe a compromise would be to leave it as it currently is and let the user override the default with a Formatter.

**Comment by cetra3** [comment]
This is something that can be handled by your own function rather than embedded in the framework:

```rust
pub fn log_error<E: Into<Error>>(err: E) -> actix_web::Error {
    let err: Error = err.into();
    error!("{:?}", err);
    err.chain()
        .skip(1)
        .for_each(|cause| error!("because: {}", cause));
    ErrorInternalServerError(err)
}
```

I don't feel it's worthy of being changed in actix-web itself for that reason.

**Comment by robjtede** [comment]
Consensus seems like a no on this one. Many logging systems assume one log per line and user-land solutions are easy enough.

**Pull request closed without merging**
