### PR TITLE
Add ability to name a handler function as 'config'

### LINKED ISSUE #1277: Cannot name function as config when using #[get] macro
```rust
use actix_web::{App, HttpResponse, HttpServer, Responder, get};

#[get("/config")]
async fn config() -> impl Responder {
    HttpResponse::Ok().body("list of configurations")
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new()
            .service(config)
    })
    .bind("127.0.0.1:8088")?
    .run()
    .await
}

```
error
```
error[E0308]: mismatched types
 --> src\main.rs:3:1
  |
3 | #[get("/config")]
  | ^^^^^^^^^^^^^^^^^ expected struct `actix_web::config::AppService`, found struct `config`
  |
  = note: expected type `actix_web::config::AppService`
             found type `config`

error[E0308]: mismatched types
 --> src\main.rs:3:1
  |
3 | #[get("/config")]
  | ^^^^^^^^^^^^^^^^^ expected mutable reference, found fn item
  |
  = note: expected type `&mut actix_web::config::AppService`
             found type `fn() -> impl std::future::Future {<config as actix_web::service::HttpServiceFactory>::register::config}`

error: aborting due to 2 previous errors
```

### PR DESCRIPTION
**Pull request by gtors**
Fixes #1277

### CODE REVIEW

**Review by cetra3 — APPROVED** [review]
Looks good to me.

**Comment by oronsh** [comment]
Can you guys share please why this is happened? I'm very interested to know 👍

**Comment by JohnTitor** [comment]
(off-topic: @robjtede Please do not drop `waiting-on-review` label even if one reviewer approves it. Other reviewers may have different views.)

**Comment by gtors** [comment]
> Can you guys share please why this is happened? I'm very interested to know +1

@oronsh  name collision with variable generated via procedural macros

**Review by JohnTitor — APPROVED** [review]
Could you also update changes.md with the PR number and link?

**Comment by gtors** [comment]
> Could you also update changes.md with the PR number and link?

Sure

**Comment by JohnTitor** [comment]
Ah, you should update changes.md in actix-web-codegen, not in the root.

**Comment by gtors** [comment]
> Ah, you should update changes.md in actix-web-codegen, not in the root.

My bad

**Comment by gtors** [comment]
Done

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
