### PR TITLE
Fix peer addr string

### LINKED ISSUE #1095: ConnectionInfo.remote() returns remote socket address not IP
The documentation in https://docs.rs/actix-web/1.0.7/actix_web/dev/struct.ConnectionInfo.html#method.remote says that it returns the IP of the peer. However, if it's obtained directly from the peer socket address, it returns also the peer socket address (e.g. `127.0.0.1:51286` and not `127.0.0.1`). This may cause real problems if this returned str value is used as is for rate limiting for example.

### PR DESCRIPTION
**Pull request by Chronophagus**
Fixes #1095

### CODE REVIEW

**Comment by fafhrd91** [comment]
I don’t have strong opinion, but this change drops some information.

@actix/contributors ?

**Comment by cetra3** [comment]
Is there a way to get the connecting port out if this change is made? I don't think losing that information is worth it as you can just split on the colon char if you want to filter to the ip.

**Comment by Chronophagus** [comment]
Well, you won't get connecting port if remote addr was resolved via headers anyway. But now I realize that someone may already depend on this behavior(that there may be a port in the string), and make use of it somehow, so this can be considered as breaking change. Anyway the docs should mention that method returns "[IP]" when remote resolved via headers, or "[IP]:[PORT]" when remote resolved via socket, because now it's unclear.

**Comment by robjtede** [comment]
Yeah I'd be worried about changing this behaviour; I've, personally, written code that parses this field and discovered the inconsistency with port numbers. Any reasonable code will try to parse it both ways but this is technically breaking in cases where port numbers are expected to always exist and be parsed out. I think a better approach could involve a new method on the impl ConnectionInfo that's guaranteed to only return the address portion.

**Comment by svenstaro** [comment]
Yeah, let's not change this. At least not in 1.0.x.

**Comment by fafhrd91** [comment]
closing after discussion. we should update docs instead

**Pull request closed without merging**
