### PR TITLE
Add doctest to verify NormalizePath middleware usage in App

### LINKED ISSUE #806: Normalize Path  doesn't appear to work with .wrap
```
actix_web::App::new()
            .wrap(actix_web::middleware::Compress::default())
            .wrap(actix_web::middleware::NormalizePath::default())
```
Results in the following output 
```
error[E0277]: the trait bound `actix_web::middleware::normalize::NormalizePath: actix_service::transform::IntoTransform<_, <impl actix_service::NewService as actix_service::NewService>::Service>` is not satisfied
  --> src/main.rs:59:14
   |
59 |             .wrap(actix_web::middleware::NormalizePath::default())
   |              ^^^^ the trait `actix_service::transform::IntoTransform<_, <impl actix_service::NewService as actix_service::NewService>::Service>` is not implemented for `actix_web::middleware::normalize::NormalizePath`
```

### PR DESCRIPTION
**Pull request by DoumanAsh**
Closes #806

### CODE REVIEW

**Comment by fafhrd91** [comment]
Add this as normal test too

**Comment by DoumanAsh** [comment]
@fafhrd91 shouldn't doctest be enough?

**Comment by fafhrd91** [comment]
i'd like to have actual test

**Comment by DoumanAsh** [comment]
Well, it is already tested directly through `Service` API, but oh well, I'll see about actual test

**Review by fafhrd91 — APPROVED** [review]

**Pull request merged**
