### PR TITLE
Make current actix client demo work

### PR DESCRIPTION
**Pull request by esemeniuc**
I was unable to make the existing `client.rs` demo work as it was missing `Cargo.toml`. I have updated the demo to work out of the box.

### CODE REVIEW

**Comment by robjtede** [comment]
What command wasn’t working for you?

**Comment by esemeniuc** [comment]
I was getting `Response: Err(Connect(SslIsNotSupported))` as the openssl/rustls dependency was not explicit.

Another thing improvement is that my example does not require the `awc` or `actix_http` crates to be  explicitly added.

**Comment by robjtede** [comment]
Would be better to keep the example in this repo as a single file and maybe guard the main method on the requred feature with an alternative main method showing the command needed to run it properly.

**Comment by JohnTitor** [comment]
So the problem here is root Cargo.toml doesn't have an entry for the client example.
You should add this instead of adding another `Cargo.toml`:
```toml
[[example]]
name = "client"
required-features = ["rustls"]
```

**Comment by robjtede** [comment]
closing in favor of #1625

**Pull request closed without merging**
