### PR TITLE
add pub use crate::app_service::AppEntry;

### PR DESCRIPTION
**Pull request by singersbalm**
## PR Type

Other

## Overview

Just makes AppEntry public for usage in functions. example: ` fn register(&self, app: App<AppEntry>) -> App<AppEntry>;`

### CODE REVIEW

**Comment by robjtede** [comment]
see https://github.com/actix/actix-web/issues/780#issuecomment-894704144

**Comment by singersbalm** [comment]
@robjtede and how can i use it with a trait?

```
cannot be made into an object Note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically

**Comment by robjtede** [comment]
can you post full errors please

**Comment by singersbalm** [comment]
```
error[E0038]: the trait `B` cannot be made into an object
  --> src/lib.rs:18:45
   |
18 |     pub data: Arc<Mutex<dyn B + Send + 'static>>,
   |                                             ^^^^^^^^^^^^^^^^^ `B` cannot be made into an object
   |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
  --> src/lib.rs:44:8
   |
42 | pub trait B {
   |           ------- this trait cannot be made into an object...
44 |     fn register<T: ServiceFactory<
   |        ^^^^^^^^ ...because method `register` has generic type parameters
   = help: consider moving `register` to another trait

```
Code
```rs
pub struct A {
    pub data: Arc<Mutex<dyn B + Send + 'static>>,
}

pub trait  B {
    fn register<T: ServiceFactory<
        ServiceRequest,
        Response=ServiceResponse<impl MessageBody>,
        Config=(),
        InitError=(),
        Error=Error,
    >>(&self, app: App<T>) -> App<T>;
}
```

**Comment by robjtede** [comment]
Would it be okay for you to use:
```rust
    fn register<
        T: ...
    >(&self, app: App<T>) -> App<T>
    where
        Self: Sized;
```

**Comment by singersbalm** [comment]
i tried it with sized, but it seems like this wont work. 
```rs
error: the `register` method cannot be invoked on a trait object
  --> src/main.rs:35:37
   |
35 |             app = v.lock().unwrap().register(app);
   |                                     ^^^^^^^^
   |
  ::: src/lib.rs:51:50
   |
51 |     >>(&self, app: App<T>) -> App<T> where Self: Sized {
   |                                                  ----- this has a `Sized` requirement


```

**Comment by robjtede** [comment]
Ahh. I'd hoped you wouldn't need that method behind a dyn reference.

**Comment by singersbalm** [comment]
any ideas what could solve this?

**Pull request closed without merging**
