### PR TITLE
prepare v4 beta releases

### PR DESCRIPTION
**Pull request by robjtede**

### CODE REVIEW

**Review by fakeshadow — APPROVED** [review]
LGTM

**Comment by tyranron** [comment]
@robjtede hi, any ETAs for releasing stable 4.0 with the ecosystem bump? Any help for that?

Actix with its ecosystem is the only thing which makes us sit on tokio 0.2 still. Would love to move forward.

Thanks!

**Comment by robjtede** [comment]
Here's the v4 milestone but this is by no means an exhaustive list. There are many TODOs in the codebase and open issues that will be added also.
https://github.com/actix/actix-web/milestone/6

At the moment I am concentrating on getting actix-rt stable so that some libs (eg. sqlx) can update.

I estimate 3 weeks until v4 is possible.

**Comment by tyranron** [comment]
@robjtede thanks!

**Pull request merged**
