### PR TITLE
Allow to override Form extractor error

### PR DESCRIPTION
**Pull request by ghost**
#302

### CODE REVIEW

**Comment by fafhrd91** [comment]
looks good! but could you add test?

**Comment by ghost** [comment]
is there an example of something like this?

**Comment by fafhrd91** [comment]
you can use similar test that you added for other ticket. just send malformed data, and on server configure custom error handle.

does it make sense?

**Comment by ghost** [comment]
ok got it. I couldn't find how to configure custom error handle. just found it

**Comment by ghost** [comment]
```
#[test]
fn test_form_extractor2() {
    let mut srv = test::TestServer::new(|app| {
        app.resource("/{username}/index.html", |r| {
            r.route().with(|form: Form<FormData>| {
                format!("{}", form.username)
            }).error_handler(|err, res| {
                error::InternalError::from_response(
                    err, HttpResponse::Conflict().finish()).into()
            })
        });
    });

    // client request
    let request = srv
        .post()
        .uri(srv.url("/test1/index.html"))
        .header("content-type", "application/x-www-form-urlencoded")
        .body("918237129hdk:D:D:D:D:D:DjASHDKJhaswkjeq")
        .unwrap();
    let response = srv.execute(request.send()).unwrap();
    assert!(response.status().is_client_error());
}
```
I wrote this, but I get this error:
error[E0597]: borrowed value does not live long enough
   --> tests\test_handlers.rs:132:13
    |
132 | /             r.route().with(|form: Form<FormData>| {
133 | |                 format!("{}", form.username)
134 | |             }).error_handler(|err, res| {
    | |______________^ temporary value does not live long enough
...
138 |           });
    |           -- temporary value needs to live until here
    |           |
    |           temporary value dropped here while still borrowed

**Comment by fafhrd91** [comment]
```rust
app.resource("/{username}/index.html", |r| {
            r.route().with(|form: Form<FormData>| {
                format!("{}", form.username)
            }).error_handler(|err, res| {
                error::InternalError::from_response(
                    err, HttpResponse::Conflict().finish()).into()
            });  // <-- I think you miss this
        });
```

**Comment by ghost** [comment]
untitled

**Comment by ghost** [comment]
ok thanks

**Review by fafhrd91 — APPROVED** [review]

**Comment by ghost** [comment]
wow. thanks for inviting me

**Comment by fafhrd91** [comment]
you should have permission to merge when travis succeed

**Pull request merged**
