### PR TITLE
Remove several uses of `Pin::new_unchecked`

### PR DESCRIPTION
**Pull request by Aaron1011**
Most of the relevant struct already had a `#[pin_project]` attribute,
but it wasn't being used.

The remaining uses of `Pin::new_unchecked` all involve going from a
`&mut T` to a `Pin<&mut T>`, without directly observing a `Pin<&mut T>`
first. As such, they cannot be replaced by `pin_project`

### CODE REVIEW

**Comment by cdbattags** [comment]
@robjtede and @JohnTitor, what are y'all's thoughts on this?

I'm good with this change but we might need to be explicit somewhere what this macro is doing either in docs or some write-up?

**Review by cdbattags — APPROVED** [review]

**Comment by robjtede** [comment]
Moving this stuff over to pin-project is definitely the way to go.

Not comfortable in myself approving until there's some kind of tests covering the changes or a more thorough investigation than just eyeballing it.

**Comment by Aaron1011** [comment]
> or a more thorough investigation than just eyeballing it.

The changes I've made are all purely mechanical. The [pin-project docs](https://docs.rs/pin-project/0.4.8/pin_project/) go into more detail about how each of the attributes work.

**Comment by cetra3** [comment]
Is there any test coverage we have for this? I don't know how the semantics change with the new `Drop` signature.

I.e, can we construct a `OpenWaitingConnection` that isn't pinned & then leak out resources if it's dropped normally.

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
The semantics don't change with the PinnedDrop impl, it's required to use with pin-project to protect against unsafe Drop impls. 

Given the changes a good look over and am happy.

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
