### PR TITLE
prepare http-2.0.0-beta.1 release

### PR DESCRIPTION
**Pull request by robjtede**

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Let's go ahead :)
Also, I'd like to update http's version on other places.

**Comment by robjtede** [comment]
Yup! Sure thing. I'm not used to how this works for a larger project with intertwining dependencies but seemed like a good place to start with http.

**Comment by robjtede** [comment]
Fairly certain I don't have access rights to publish crates? @JohnTitor lets get a round out ASAP.

**Comment by fafhrd91** [comment]
you should be able to. anyone from Core team should be able to push new releases

**Comment by robjtede** [comment]
Alright, thanks @fafhrd91; crates.io doesn't seem to give any indication of it. I'll give it a go.  
Edit: ahh i see it on the project page, was expecting it to show up near "my crates".

**Comment by therealprof** [comment]
It's a pity that rustls wasn't updated before. Is that already in the works or should I PR it?

**Comment by JohnTitor** [comment]
@therealprof It should be started from actix-net crates first, I already opened https://github.com/actix/actix-net/pull/154 and will do here after merging and shipping them.

**Pull request merged**
