### PR TITLE
prepare actix-web v3.0.0-beta.1 release

### PR DESCRIPTION
**Pull request by robjtede**
bumps actix-web and codegen versions for release

### CODE REVIEW

**Comment by robjtede** [comment]
There may be other things we want to bump before this?

**Comment by Silentdoer** [comment]
app_data should be rename?

**Comment by robjtede** [comment]
Not in this PR. Let's keep discussions of specific items to their issues.

**Review by JohnTitor — APPROVED** [review]
Though it's a dev-dep, it still refers alpha - let's sync :)

https://github.com/actix/actix-web/blob/2065c4744afd670e3313c6944ea250e6f5a3b602/awc/Cargo.toml#L59

Otherwise looks good to me.

**Pull request merged**
