### PR TITLE
prepare codegen 0.4.0 release

### PR DESCRIPTION
**Pull request by robjtede**
## PR Type
Release

## PR Checklist
- [x] A changelog entry has been made for the appropriate packages.
- [x] Documentation comments have been added / updated.

## Overview
Releasing as 0.4.0 as actix-web does not automatically use it, given a short public trial period we can bump the dependency in actix-web to use this.

### CODE REVIEW

**Comment by robjtede** [comment]
interesting... trybuild failures because it doesn't respect local patches or something, will check before progressing

**Comment by robjtede** [comment]
Problem with trybuild was because tests used `actix_web::*` re-exports; have changed that and tweaked some of the stderr files accordingly.

Revamped the main page documentation for folks who land on the codegen docs.

Tweaked some of the attribute docs to encourage use of actix_web re-exports while keeping doc tests using self versions. Weird case here is `actix_web_codegen::main` which can't simply be refered to as `#[main]` because compiler says no; a clarification is given.

**Comment by robjtede** [comment]
Alright, tests are passing 🎉 ready for a review @actix/contributors

**Review by Neopallium — APPROVED** [review]
Looks good.

**Pull request merged**
