### PR TITLE
Form impls responder

### LINKED ISSUE #995: Implement Responder for Form to return url-encoded data
Json implements Responder to return application/json data. By symmetry, I think Form should implement Responder to return application/x-www-form-urlencoded data.

url-encoded isn't used as much any more but is probably still useful in some cases.

### PR DESCRIPTION
**Pull request by jesskfullwood**
Closes #995

### CODE REVIEW

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
You should have permission to merge

**Comment by jesskfullwood** [comment]
> You should have permission to merge

I don't think so.. can't see a button, just 
```
This pull request can be automatically merged by project collaborators
Only those with write access to this repository can merge pull requests.
```

**Comment by fafhrd91** [comment]
I sent you invitation to contributors team

**Comment by jesskfullwood** [comment]
Ah thanks, appreciate it!

**Pull request merged**
