### PR TITLE
Basic Ranges header support

### PR DESCRIPTION
**Pull request by ghost**
As mentioned earlier, I reopen this PR, with modifications you asked, also fixed some other things, and formatted a bit.

The only thing I'm not 100% sure is the following:

```if let Ok(ranges) = HttpRange::parse(rangeheader.to_str().unwrap_or(""), file_metadata.len())```

In theory if the header is not convertable to str(not possible in theory, but I'm taking your side: better safe than sorry)  somehow, it will give back a empty string on error which cant be parsed therefore the parse function is failing and finally generating a 416 Error.

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you rebase this PR.

regarding `HttpRange::parse()` if it can not parse header we should return 400 response

**Comment by fafhrd91** [comment]
sorry, i did some work on static files, it provides more functionality

**Comment by ghost** [comment]
No problem, I'll refactor the code as well.

**Comment by fafhrd91** [comment]
Any updates?

**Comment by fafhrd91** [comment]
No activity

**Pull request closed without merging**
