### PR TITLE
NamedFile: added basic ranges header support, added content-length support

### PR DESCRIPTION
**Pull request by ghost**
I added support for the content-length for the NamedFile, since this can be important with big files, since it helps the client to decide to get a whole file or specific chunks from it.

I also added some ranges support as mentioned in #60 . I'm not expecting this getting merged as-is, since I had to modify a helper-type, it works however but not something I'm happy with right now. I shared it with you with the hopes of you'll have a better idea how to do implement this.

I also modified the disposition of the Video types, since it's making sense to watch a video in your browser. To me at least.

There's also some bugginess with the "accept-ranges: bytes" header, since it causing some error messages, and I didn't found the root cause of these, even with a packetcapturing. I'll work on this some more for sure.

### CODE REVIEW

**Comment by fafhrd91** [comment]
looks good. but could you add test for range response

**Comment by ghost** [comment]
*sigh* oh dear github...

Added test for status code, content-length header, and  range response header.

**Comment by fafhrd91** [comment]
something is wrong with PR, rebase or squash maybe?

**Comment by fafhrd91** [comment]
ping

**Comment by ghost** [comment]
I'm working on it. Somehow a pull messed up my git tree.

**Comment by ghost** [comment]
Should be fine by now.

**Comment by fafhrd91** [comment]
thanks!

**Pull request merged**
