### PR TITLE
Named file service

### LINKED ISSUE #2115: actix_files : easy default file
## Expected Behavior

It would be nice being able to write 

```rust
App::new()
            .service(
                actix_files::Files::new("/", "./static/")
                    .prefer_utf8(true)
                    .index_file("index.html")
                    .default_handler(actix_files::NamedFile::open("./static/index.html")))
```

or even

```rust
App::new()
            .service(
                actix_files::Files::new("/", "./static/")
                    .prefer_utf8(true)
                    .index_file("index.html")
                    .default_file("index.html"))
```

## Current Behavior
Currently, one has to write 

```rust
    HttpServer::new(|| {
        App::new()
            .service(
                actix_files::Files::new("/", "./static/")
                    .prefer_utf8(true)
                    .index_file("index.html")
                    .default_handler(|req: ServiceRequest| {
                        let (http_req, _payload) = req.into_parts();

                        async {
                            let response = actix_files::NamedFile::open("./static/index.html")?.into_response(&http_req)?;
                            Ok(ServiceResponse::new(http_req, response))
                        }
                    }))
```

Unless there is a better way to serve an SPA ? I didn't find it in the docs.

## Context

It is common to to have Single-Page Applications where some of the routing is done on the client-side. In that case, one wants to always serve the index page, whatever the requested route. Currently, doing so is more complex and verbose than it could be (except if I missed something in the documentation...).

### PR DESCRIPTION
**Pull request by ibraheemdev**
## PR Type
Feature

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

Closes #2115

### CODE REVIEW

**Comment by robjtede** [comment]
Neat, I like this feature.

Definitely would like an example of it in use, maybe on the docs for `Files::default_handler`.

**Comment by ibraheemdev** [comment]
@robjtede Okay, is the implementation fine?

**Comment by robjtede** [comment]
> is the implementation fine?

Looks like it yeah. We'll see for certain with a test of success case response and error case like missing file.

**Comment by ibraheemdev** [comment]
Would it make sense to implement `HttpServiceFactory` as well?

**Comment by robjtede** [comment]
> Would it make sense to implement HttpServiceFactory as well?

Sure, if it can fit into `service` and `default_service` too it would make serving SPAs simpler.

**Comment by ibraheemdev** [comment]
Tests added.

**Comment by svenstaro** [comment]
Can you rebase this to it merged? I think this is a neat little service that I'd like to see go to mainline. :)

**Review by robjtede — APPROVED** [review]
lgtm

**Comment by lovasoa** [comment]
Thanks !

**Pull request merged**
