### PR TITLE
WIP: Update to Tokio 0.2

### PR DESCRIPTION
**Pull request by martell**
Update to tokio 0.2

Blocked on https://github.com/actix/actix-net/pull/66

### CODE REVIEW

**Comment by fafhrd91** [comment]
i dont understand, why is this here? it is not even compiles

**Comment by shirshak55** [comment]
@fafhrd91 may be he is working on moving codebase to tokio 0.2 ?

**Comment by martell** [comment]
Sorry, I meant to make this a draft  PR, github doesn't seem to give the ability to change that currently but I could be wrong. the WIP - means work in progress, it is not ready yet.

**Comment by fafhrd91** [comment]
master is on tokio 0.2

**Pull request closed without merging**
