### PR TITLE
Customize websocket max size

### PR DESCRIPTION
**Pull request by kingxsp**

### CODE REVIEW

**Comment by fafhrd91** [comment]
i dont want to add extra public api function just for one param. it only saves couple lines of code

**Comment by kingxsp** [comment]
Ok! But is there any other way to set the max_size value?
```
fn ws_index(r: HttpRequest) -> Result<HttpResponse, Error> {
    ws::start(r, MyWebSocket)
}
```

**Comment by fafhrd91** [comment]
you can manually do handshake and create WebsocketContext

**Comment by kingxsp** [comment]
Ok！

**Comment by CamJN** [comment]
@fafhrd91 Can you elaborate on how to manually do the handshake and create the WebsocketContext, especially in relation to the https://github.com/actix/examples/tree/master/websocket-chat example?

The docs at https://actix.rs/actix-web/actix_web/ws/fn.handshake.html are really minimal.

**Pull request closed without merging**
