### PR TITLE
deprecate builder if-x methods

### PR DESCRIPTION
**Pull request by robjtede**
## PR Type
Deprecation

## PR Checklist
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt

## Overview
These methods serve little purpose where standard if-let constructions exists.

### CODE REVIEW

**Review by popzxc — APPROVED** [review]
👍

**Review by jplatte — APPROVED** [review]
I guess the point was that you wouldn't need to bind the builder to a local variable with this in almost all cases. But I agree it's a bit weird and wouldn't personally use it because of that.

**Comment by pka** [comment]
I'm struggling to find a replacement for the following `if_true` usage:
```rust
HttpResponse::Ok()
    .content_type("application/x-protobuf")
    .if_true(gzip, |r| {
        // data is already gzip compressed
        r.encoding(ContentEncoding::Identity)
            .header(header::CONTENT_ENCODING, "gzip");
    })
    .header(header::CACHE_CONTROL, format!("max-age={}", cache_max_age))
    .body(tile)
```

As soon as I split this into multiple statements I get `error[E0716]: temporary value dropped while borrowed` for the `ResponseBuilder` object, which isn't easy to solve.

**Comment by robjtede** [comment]
~I admit this is a little ugly:~ Edit: improved.

```rust
let mut res = HttpResponse::Ok();
res.header(header::CACHE_CONTROL, format!("max-age={}", cache_max_age));
res.content_type("application/x-protobuf");

if gzip {
    // data is already gzip compressed
    res.encoding(ContentEncoding::Identity)
        .header(header::CONTENT_ENCODING, "gzip");
}

res.body(tile)
```

**Comment by pka** [comment]
Thanks @robjtede, this is working!

**Pull request merged**
