### PR TITLE
remove unnecessary use of unsafe in read_from_io

### PR DESCRIPTION
**Pull request by gnzlbg**

### CODE REVIEW

**Review by fafhrd91 — APPROVED** [review]
Good! But we need to bench this

**Comment by fafhrd91** [comment]
I sent you invitation, you should be able to merge yourself

**Comment by gnzlbg** [comment]
I have some time to upgrade the benchmarks tomorrow, so will send a PR there to update them, and then use the one you recommended on gitter to bench this. I'll update this with the results before merging.

**Comment by fafhrd91** [comment]
Could you also modify this code?

https://github.com/actix/actix-web/blob/master/src/server/h1.rs#L439

**Comment by fafhrd91** [comment]
@gnzlbg there is no reason for this function anymore, could you just inline code?

**Comment by gnzlbg** [comment]
> Could you also modify this code?

Yes, I'll give it a shot. Will update this PR and ping you when its done :)

**Comment by fafhrd91** [comment]
i played a bit more with this patch. this patch changes semantics and i think there is performance penalty.

i am going to revert it. at this point i am not sure it is worse of removing this particular unsafe

**Comment by gnzlbg** [comment]
How did it change semantics? When I ran it all tests passed, so maybe I could add a test for the old semantics.

**Comment by fafhrd91** [comment]
h1 parsers reads all data that available in socket. That is the reason for loop. Problem with this code is that it is very os specific

**Pull request merged**
