### PR TITLE
add interval check for payload pending

### LINKED ISSUE #1313: A Stream object in a pending state won't be dropped after the client disconnect
I'm not sure if it was intended, but a `Stream` object in a pending state won't be dropped after the client disconnects.

I found this issue in `actix-web 2.0.0` and created a small test program like below:
https://github.com/masnagam/rust-case-studies/blob/master/actix-web-streaming-and-tcp-disconnect/src/main.rs

When executing the following command:

```console
timeout 3 curl -v http://localhost:3000/pending
```

we never see `PendingStream: Dropped` in the log messages from the test program.

If a stream returns a `Poll::Ready`, it will be dropped shortly. We can see that by executing:

```console
timeout 3 curl -v http://localhost:3000/alternate
```

Is there any workaround to stop polling the pending stream shortly when the client disconnects?

### PR DESCRIPTION
**Pull request by fakeshadow**
## PR Type

Feature

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

Add interval check(1 second) on Io stream's read status when response payload stream enters pending.
When interval check detect Io is not readable anymore it would assume remote client have disconnect and end dispatcher. All unfinished responses would be lost.

Closes #1313

### CODE REVIEW

**Comment by fakeshadow** [comment]
Draft this for now until finding a way to detect client disconnect

**Comment by fakeshadow** [comment]
Should this active across aboard or put behind a feature gate?

**Comment by robjtede** [comment]
What's the rationale for wanting a feature flag? You expect a perf hit?

**Comment by fakeshadow** [comment]
I suspect this could conflict with user keep alive code like a longer heartbeat they define with extra logic on heartbeat expire. This could end the connection before their heartbeat logic kick in hense breaking.

I'm not sure about this though just a guess.

**Comment by kmyers608** [comment]
Is there anything I can help with to move this forward? We believe that this issue is the root cause behind an issue we have been running into running actix behind envoy.

**Comment by fakeshadow** [comment]
> Is there anything I can help with to move this forward? We believe that this issue is the root cause behind an issue we have been running into running actix behind envoy.

Thanks for asking.

I want to make a bit clearify that this PR is not an issue fix but mostly a feature(a hacky one).

The problem of this feature is it goes against convensional handing of Rust future/stream type and may cause problem for people expecting otherwise. Like this https://github.com/actix/actix-web/pull/2032#issuecomment-809375785 discussed.

It would be pretty hard to test the possibility of break people code so I tend to give this PR sometime and potentially make it a gated feature that is opt-in. 

Edit: It would be appreciated to help test and/or help putting this behind a feature. I would try to keep this PR in sync with master

**Comment by fakeshadow** [comment]
I don't have time to keep up the sync with master branch anymore.
This PR would be left where it's now and anyone feel like to can pick it up or make a new one for the same feature.

**Pull request closed without merging**
