### PR TITLE
export handler::Handler

### PR DESCRIPTION
**Pull request by sergeysova**
I want to implement a custom Factory to strictly define arguments for handlers

```rust
impl<F, B, T, R, O> Handler<F, T, R, O>
where
    F: BoundFactory<B, T, R, O>,
    R: Future<Output = O>,
    O: Responder,
{
    pub fn new(hnd: F) -> Self {
        Handler {
            hnd,
            _t: PhantomData,
        }
    }
}


pub trait BoundFactory<B, T, R, O>: Clone + 'static
where
    R: std::future::Future<Output = O>,
    O: actix_web::Responder,
{
    fn call(&self, bound: B, param: T) -> R;
}

impl<Func, B0, R, O> BoundFactory<(B0,), (), R, O> for Func
where
    Func: Fn(B0) -> R + Clone + 'static,
    R: std::future::Future<Output = O>,
    O: actix_web::Responder,
{
    fn call(&self, bound: (B0,), _: ()) -> R {
        (self)(bound.0)
    }
}
impl<Func, B0, A0, R, O> BoundFactory<(B0,), (A0,), R, O> for Func
where
    Func: Fn(B0, A0) -> R + Clone + 'static,
    R: std::future::Future<Output = O>,
    O: actix_web::Responder,
{
    fn call(&self, bound: (B0,), args: (A0,)) -> R {
        (self)(bound.0, args.0)
    }
}

impl<Func, B0, B1, R, O> BoundFactory<(B0, B1), (), R, O> for Func
where
    Func: Fn(B0, B1) -> R + Clone + 'static,
    R: std::future::Future<Output = O>,
    O: actix_web::Responder,
{
    fn call(&self, bound: (B0, B1), _: ()) -> R {
        (self)(bound.0, bound.1)
    }
}

impl<Func, B0, B1, A0, A1, R, O> BoundFactory<(B0, B1), (A0, A1), R, O> for Func
where
    Func: Fn(B0, B1, A0, A1) -> R + Clone + 'static,
    R: std::future::Future<Output = O>,
    O: actix_web::Responder,
{
    fn call(&self, bound: (B0, B1), args: (A0, A1)) -> R {
        (self)(bound.0, bound.1, args.0, args.1)
    }
}
```

### CODE REVIEW

**Comment by cetra3** [comment]
I think `Handler` is an internal struct and should remain that way.

You can use `Service` instead to accomplish what you can do. I had a PR to [simplify this down a bit](https://github.com/actix/actix-web/pull/1275), but was closed.

**Comment by sergeysova** [comment]
@cetra3 Can you show me example with `Service` please?

**Comment by cetra3** [comment]
@sergeysova see my PR.

**Comment by sergeysova** [comment]
@JohnTitor what do you think?

I tries to implement actix-swagger(cargo-swagg) code generator. I need a factory with required arguments.

**Comment by cdbattags** [comment]
> I think `Handler` is an internal struct and should remain that way.
> 
> You can use `Service` instead to accomplish what you can do. I had a PR to [simplify this down a bit](https://github.com/actix/actix-web/pull/1275), but was closed.

I agree with this sentiment I believe this can already be done

**Comment by sergeysova** [comment]
Can you show me an example, I want to define Factory with required arguments and types and some optional rest.

For example:

```rust
fn my_handler(body: web::Json<Type>, another: Another) {}

fn handler2(body: web::Json<Type>, app: web::Data<App>) {}

fn handler3(body: web::Json<Type>) {}

fn handler_wr(body: web::Json<Another>) {}
```

I want to have some method, that receives any function that have first argument of specified type, and rest arguments just impl FromRequst.

```rust
// ok
bind_handler(my_handler);
bind_handler(handler2);
bind_handler(handler3);

// fail
bind_handler(handler_wr);
```

**Comment by robjtede** [comment]
@sergeysova is this still something you need access to?

**Comment by sergeysova** [comment]
@robjtede yes. It should be useful

**Comment by robjtede** [comment]
@sergeysova Ok, what's the reason that the exposed `Factory` trait isnt enough? Seems weird that a struct would be useful to you in this.

**Pull request closed without merging**
