### PR TITLE
web: Bump up to 3.0.0-beta.2

### PR DESCRIPTION
**Pull request by JohnTitor**

### CODE REVIEW

**Comment by robjtede** [comment]
shouldnt we also bump awc version?

**Comment by therealprof** [comment]
@robjtede Yes, please. Would also be nice if we could get the rustls bump some time...

**Comment by JohnTitor** [comment]
Well, it's not necessary, I think. Any notable changes there?

**Comment by robjtede** [comment]
Isn't it just to get the -http versions the same?

**Comment by JohnTitor** [comment]
We can already pull actix-http 2.0.0-beta.3, cannot we? I think it's enough here to avoid making release harder.

**Review by robjtede — APPROVED** [review]

**Comment by JohnTitor** [comment]
@robjtede Thanks for tagging it, do you mind publish a release, too?

**Pull request merged**
