### PR TITLE
release 4.1 group

### PR DESCRIPTION
**Pull request by robjtede**
## PR Type

Releases

## PR Checklist

- [x] A changelog entry has been made for the appropriate packages.
- [x] (Team) Label with affected crates and semver status.

### CODE REVIEW

**Comment by robjtede** [comment]
@JohnTitor If you're happy with this would you mind publishing them to crates.io too, please. GitHub releases are drafted.

**Review by JohnTitor — APPROVED** [review]
👍

**Comment by JohnTitor** [comment]
Hmm, I've encountered https://github.com/gyscos/zstd-rs/issues/147 and I cannot publish actix-http and -web.
Because actix-http will use the published version of actix-web when publishing, an error like below occurs:
```
  failed to select a version for `zstd`.
      ... required by package `actix-http v3.1.0`
  versions that meet the requirements `^0.11` are: 0.11.2+zstd.1.5.2, 0.11.1+zstd.1.5.2, 0.11.0+zstd.1.5.2

  the package `zstd` links to the native library `zstd`, but it conflicts with a previous package which links to `zstd` as well:
  package `zstd-safe v4.1.4+zstd.1.5.2`
      ... which satisfies dependency `zstd-safe = "=4.1.4"` of package `zstd v0.10.0+zstd.1.5.2`
      ... which satisfies dependency `zstd = "^0.10"` of package `actix-http v3.0.0`
      ... which satisfies dependency `actix-http = "^3.0.0"` of package `actix-web v4.0.0`
      ... which satisfies dependency `actix-web = "^4"` of package `actix-http v3.1.0`
```

@robjtede Any idea? Maybe we could disable the -web dev-dep on -http temporarily? Or `actix-web = { git = "https://github.com/actix/actix-web", rev = "43671ae4aaf2c20150fd1e5ca54055eb5d114273" }`?

**Comment by JohnTitor** [comment]
Avoided the issue with this: https://github.com/actix/actix-web/commit/392641658064469609edd366b6ad11c343ea0c88

**Pull request merged**
