### PR TITLE
Make JsonConfig send

### LINKED ISSUE #827: Make JsonConfig Send
JsonConfig is not Send:

```rust
// ...

pub struct JsonConfig {
    limit: usize,
    ehandler: Option<Rc<Fn(JsonPayloadError, &HttpRequest) -> Error>>, // <- Rc is not Send
}

// ...
```

This does not allow to share the config instance between workers causing each worker to have its own copy of the JsonConfig instance.

e.g. the following snippet does not compile:

```rust
// ...

pub fn instance_json_config() -> JsonConfig {
  // ...
}

pub fn main() -> io::Result<()> {
    let server_address = env::var("SERVER_ADDRESS").unwrap();
    let server_workers = env::var("SERVER_WORKERS").unwrap().parse().unwrap();
    let state = AppState::new();

    let json_config = Arc::new(instance_json_config());

    HttpServer::new(move || {
        App::new()
            .data(state.clone())
            .data(json_config.clone())
            .configure(app_router)
    })
    .workers(server_workers)
    .bind(server_address)?
    .run()
}
```

So I ended up writing something like that:

```rust
// ...

pub fn instance_json_config() -> JsonConfig {
  // ...
}

pub fn main() -> io::Result<()> {
    let server_address = env::var("SERVER_ADDRESS").unwrap();
    let server_workers = env::var("SERVER_WORKERS").unwrap().parse().unwrap();
    let state = AppState::new();

    HttpServer::new(move || {
        App::new()
            .data(state.clone())
            .data(instance_json_config())
            .configure(app_router)
    })
    .workers(server_workers)
    .bind(server_address)?
    .run()
}
```

which in turns will create a json config for each worker.

Is there another way to achieve that or am I missing something?

### PR DESCRIPTION
**Pull request by daddinuz**
Fixes #827 

Note that `ehandler` now must be Send + Sync, I don't know if this may cause compatibility issues:

```rust
// ...

pub struct JsonConfig {
    limit: usize,
    ehandler: Option<Arc<Fn(JsonPayloadError, &HttpRequest) -> Error + Send + Sync>>, // <--
}

// ...
```

### CODE REVIEW

**Comment by daddinuz** [comment]
Just discovered that there is an issue when registering an `Arc<JsonConfig>` with `App::data`.

`FromRequest` is implemented for `Json<T>` with associated `type Config = JsonConfig`, so the call to  `app_data::<JsonConfig>` to retrieve the configs inside the method `FromRequest::from_request` will return a None option because type `JsonConfig` != `Arc<JsonConfig>`.

Any suggestions?

**Comment by daddinuz** [comment]
I've found a solution that I have implemented in this [branch](https://github.com/actix/actix-web/compare/master...daddinuz:register_raw_app_data):

Since `Data` internally wraps the value in `Arc`, we could wrap `JsonConfig` in `Data` instead of `Arc`, avoiding also a double indirection.

I noticed that by now there is only `App::data` which takes an arbitrary object and internally wraps it into `Data`, so I have just added the method `register_data` which takes an instance of `Data` directly and store it in the `App`.

So, instead of writing (as in the issue example):

```rust
// ...

pub fn instance_json_config() -> JsonConfig {
  // ...
}

pub fn main() -> io::Result<()> {
    let server_address = env::var("SERVER_ADDRESS").unwrap();
    let server_workers = env::var("SERVER_WORKERS").unwrap().parse().unwrap();

    let state = AppState::new();
    let json_config = Arc::new(instance_json_config());

    HttpServer::new(move || {
        App::new()
            .data(state.clone())
            .data(json_config.clone())
            .configure(app_router)
    })
    .workers(server_workers)
    .bind(server_address)?
    .run()
}
```

I would write:

```rust
use actix_web::web::Data;

// ...

pub fn instance_json_config() -> JsonConfig {
  // ...
}

pub fn main() -> io::Result<()> {
    let server_address = env::var("SERVER_ADDRESS").unwrap();
    let server_workers = env::var("SERVER_WORKERS").unwrap().parse().unwrap();

    let state = AppState::new();
    let json_config = Data::new(instance_json_config());

    HttpServer::new(move || {
        App::new()
            .data(state.clone())
            .register_data(json_config.clone())
            .configure(app_router)
    })
    .workers(server_workers)
    .bind(server_address)?
    .run()
}
```

solving [this](https://github.com/actix/actix-web/pull/830#issuecomment-490676508).

**Comment by fafhrd91** [comment]
@daddinuz could you add entry to changes.md

you dont change anything, just use Data<JsonConfig>, `Into<Data<T>>` for `Data<T>` returns self

**Comment by daddinuz** [comment]
@fafhrd91 sure, I'm going to update changes.md as soon as possible.

Regarding `Into<Data<T>> for Data<T>` this is will not work because there would be conflicting implementations since `From` trait is already implemented for `Data<T>`

**Comment by fafhrd91** [comment]
let's add register_data in separate PR

**Comment by fafhrd91** [comment]
actually, let's wait with register_data. for now `JsonConfig` could implement `Clone`

**Comment by daddinuz** [comment]
Ok I've added entires to CHANGES.md and updated the branch to the latest master

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
thanks!

**Pull request merged**
