### PR TITLE
bump msrv to 1.40

### PR DESCRIPTION
**Pull request by robjtede**

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
LGTM with one nit: could you also update the changelog of the actix-web? Also, I believe some packages' READMEs/changelogs that depend on actix also have the mentions about MSRV but they're outdated. Once it resolves, feel free to merge, thanks!

**Comment by robjtede** [comment]
@JohnTitor actix-web readme only had the "badge" labelling the version, added a line in the "features".

**Comment by robjtede** [comment]
Also, the "1.39.0 - x86_64-unknown-linux-gnu" task is still showing up in the CI checks list?

**Comment by JohnTitor** [comment]
I mean, this affects some other packages, e.g. actors. We need to update their READMEs as well: https://github.com/actix/actix-web/tree/master/actix-web-actors#documentation--community-resources
Also, I think it's worth to mention in the changelogs, how about?

> Also, the "1.39.0 - x86_64-unknown-linux-gnu" task is still showing up in the CI checks list?

Because it is set as required status on GitHub. I can remove it once we merge this PR :) (UPDATE: removed.)

**Comment by robjtede** [comment]
> I mean, this affects some other packages, e.g. actors. We need to update their READMEs as well: https://github.com/actix/actix-web/tree/master/actix-web-actors#documentation--community-resources
Also, I think it's worth to mention in the changelogs, how about?

ahh, yes. agree with all of this. 👍
turns out just grepping for 1.39 missed some things, eh

**Comment by robjtede** [comment]
Ok updated all changelogs except those we migrated to extras repo. Maybe should delete those soon.

**Comment by robjtede** [comment]
happy to proceed @JohnTitor ?

**Review by JohnTitor — APPROVED** [review]
:+1:

**Pull request merged**
