### PR TITLE
fix: service macro comments

### LINKED ISSUE #3472: Services macro breaks on format due to comments
## Expected Behavior
In a semi-specific situation, formatting the code should not break the `services!` macro.

## Current Behavior
The code below compiles, but errors after the formatter is run.

## Possible Solution
(Allow empty statements in the macro? I'm not sure.)
For now, people that are affected by this problem should move the second comment somewhere else. 

## Steps to Reproduce (for bugs)
Save the following code:

``` Rust
use actix_web::{services, web, HttpResponse};

fn main() {
    
        let services = services![
            web::scope("/test")
                .route("/test2", web::get().to(|| HttpResponse::NotFound())) // A quite short comment here.
                ,
                // Another comment here.
        ];
}
```
`cargo run` => it runs
`cargo fmt && cargo run`  => it errors

## Context, Environment
None, the example works in a minimal sandbox

- Rust Version (I.e, output of `rustc -V`): rustc 1.81.0 (eeb90cda1 2024-09-04)
- Actix Web Version: 4.9.0

### PR DESCRIPTION
**Pull request by Durairaj**
## PR Type

Fix

## Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

The macro definition remains similar but explicitly allows for zero or more expressions ($($x:expr),*), making it flexible for use with or without commas.

Closes #3472

### CODE REVIEW

**Comment by robjtede** [comment]
Needs a changelog entry and test for the case in the issue.

**Comment by Durairaj** [comment]
@robjtede Added tests and changelog entry. Please could you give this a review?

**Comment by robjtede** [comment]
Optional trailing commas are already handled with the `$(,)?` clause.

It seems to me that the needed change is even simpler:

```diff
  #[macro_export]
  macro_rules! services {
+     () => {()};
+ 
      ($($x:expr),+ $(,)?) => {
          ($($x,)+)
      };
  }
```

This passes all the tests you added. The only thing it doesn't support is `services!(,)` which seems fine.

**Comment by Durairaj** [comment]
@robjtede nice one, i did by merging the handling of optional trailing commas and empty lists into a single pattern. Changed the code as per your suggestion

**Review by robjtede — APPROVED** [review]

**Pull request merged**
