### PR TITLE
added support for creating custom methods with route macro

### LINKED ISSUE #2893: Allow custom HTTP methods in route macro
Your issue may already be reported!
Please search on the [Actix Web issue tracker](https://github.com/actix/actix-web/issues) before creating one.

## Expected Behavior

You should be able to use custom HTTP methods in the `route` macro:

```rs
#[route("/my/path", method = "CREATE")]
async fn create() -> HttpResponse {
  // ...
```

This is already possible with the `web::method` function, like this:

```rs
App::new()
  .route("/", web::method(Method::from_str("CREATE").unwrap()).to(|| async { "Hello CREATE" }))
```

## Current Behavior

The code above results in the error "Unexpected HTTP method: \`CREATE\`."

## Possible Solution

The parser in `actix-web-codegen` should be made more permissive so it will allow custom methods. The parsing code is already in place in `actix-web`, so that could likely be reused.

## Context

Trying to extend my server with additional HTTP methods. Not a dealbreaker and already possible, just a little more verbosely.

## Your Environment

- Rust Version (I.e, output of `rustc -V`): rustc 1.64.0 (a55dd71d5 2022-09-19)
- Actix Web Version: 4.2.1

### PR DESCRIPTION
**Pull request by notashes**
## PR Type

An improvement to existing feature. 

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

### Current Behavior: 
```rust
#[route("/my/path", method = "CREATE")]
async fn create() -> HttpResponse {
  // ...
```
If we wish to use custom methods using the route macro, it causes panic due to Unexpected HTTP method. 

### New Behavior: 
```rust
#[route("/heya", method = "NOLAN", method = "BET", method = "GET")]
async fn manual_heya() -> impl Responder {
    HttpResponse::Ok().body("Hey there ya!\n")
}
```
This would be a valid format - and we can curl with either of the three methods (Provided it's an uppercase ASCII). 

To achieve this, I added a Custom Method in MethodTypes which supported any uppercase Method that isn't one of the standard ones. 

### Extra: 
I haven't yet added the tests and documentation for it - but I plan to do it slowly as the issue progresses. 

Closes #2893

### CODE REVIEW

**Comment by robjtede** [comment]
I'd like to avoid needing a new type in actix_web. We already have the [Method guard](https://docs.rs/actix-web/latest/actix_web/guard/fn.Method.html) which should be used for this feature.

**Comment by notashes** [comment]
> I'd like to avoid needing a new type in actix_web. We already have the [Method guard](https://docs.rs/actix-web/latest/actix_web/guard/fn.Method.html) which should be used for this feature.

Thanks. I tried to make it work. Sorry for all the bad commits. I'm not familiar with git enough. Need to brush up my skills.

**Comment by robjtede** [comment]
would be good to add at least one test for failure cases like lowercase `method = "hello"`

**Comment by notashes** [comment]
> would be good to add at least one test for failure cases like lowercase `method = "hello"`

done. added a trybuild method for that with stderr similar to other tests.

**Comment by notashes** [comment]
@robjtede sorry for the repeated small fixes. I'm having trouble testing out the trybuild tests or the github action tests in local environment hence not able to fix them in one go.

**Comment by robjtede** [comment]
It should be enough to install the 1.59.0 toolchain and run `TRYBUILD=override cargo +1.59.0 test` locally.

**Comment by notashes** [comment]
> TRYBUILD=override cargo +1.59.0 test

I tried to make it work this way earlier but always greeted with the following error: 
```bash
❯ TRYBUILD=override cargo +1.59.0 test
    Updating crates.io index
error: failed to select a version for the requirement `time = "^0.3"`
candidate versions found which didn't match: 0.3.15, 0.3.14, 0.3.13, ...
location searched: crates.io index
required by package `actix-web v4.3.0 (/home/user/actix-web/actix-web)`
```

**Comment by robjtede** [comment]
Ahh of course, need to follow what the CI does [here](https://github.com/actix/actix-web/blob/master/.github/workflows/ci.yml#L56) and [here](https://github.com/actix/actix-web/blob/master/.github/workflows/ci.yml#L69) with some tweaks for time probably.

**Review by robjtede — APPROVED** [review]
great, thanks :+1:

**Pull request merged**
