### PR TITLE
Avoid using `Path` to calculate URIs, because it doesn't do the right thing on Windows

### PR DESCRIPTION
**Pull request by radix**
I'm not *totally* sure that this is 100% correct, but it makes the tests pass for me on Windows.

### CODE REVIEW

**Comment by fafhrd91** [comment]
I don't think this is complete fix. Could you add test case with request to some nested files.
something similar to test_redirect_to_index, but for existing nested file (for example examples/basic/Cargo.toml)

**Comment by fafhrd91** [comment]
You can use path iterative https://doc.rust-lang.org/std/path/struct.Path.html#method.iter
And then join it with ‘/‘

**Comment by radix** [comment]
Thanks for the advice @fafhrd91 . I have updated the PR with your suggestion, and added a new test.

I know we discussed improving the index handling support on gitter but this is at least a quicker improvement.

**Comment by fafhrd91** [comment]
looks good.

lets do index changes as separate PR

**Comment by fafhrd91** [comment]
wait, I think there is bug

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
I think `Directory` implementation has similar bug

**Comment by fafhrd91** [comment]
merge whenever you are ready

**Comment by radix** [comment]
Okay. I was waiting for appveyor but it seems to be stuck. I'll merge and then try to look in to the other errors on windows.

**Pull request merged**
