### PR TITLE
set timeout value for connection

### PR DESCRIPTION
**Pull request by klim-iv**
## PR Type

PR_TYPE

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

### CODE REVIEW

**Comment by fakeshadow** [comment]
Connector's timeout is used for the first establish of a tcp connection (include tls handshake).

awc's timeout is used for actual http request timeout using the tcp connection connector gives you. They have different meaning and you should not mix them as a single timeout.

If you want to modify the connector's timeout setting you should construct a Connector and pass it to awc's Builder with this API:
https://github.com/actix/actix-web/blob/6a29a50f25fd103c61e93d97dbee5745640bb911/awc/src/builder.rs#L69
You can set a single duration if you want to but you should aware that they are different timeout for different usage. (Normally you don't want a large duration for first establish of connection so give a relative lower timeout to connector is prefered.)

**Comment by klim-iv** [comment]
> Connector's timeout is used for the first establish of a tcp connection (include tls handshake).
> awc's timeout is used for actual http request timeout using the tcp connection connector gives you. They have different meaning and you should not mix them as a single timeout.

yes, I understand. In my case, dns-resolver is working slow , 1s is not enough for **connect** timeout (may be need to increase default value?)

> If you want to modify the connector's timeout setting you should construct a Connector and pass it to awc's Builder with this API:
> 
> https://github.com/actix/actix-web/blob/6a29a50f25fd103c61e93d97dbee5745640bb911/awc/src/builder.rs#L69
> 
> You can set a single duration if you want to but you should aware that they are different timeout for different usage. 

Thanks, I'll try, but maybe better to little bit increase connect-timeout in default values? (1s-> 3s)

**Comment by fakeshadow** [comment]
> Thanks, I'll try, but maybe better to little bit increase connect-timeout in default values? (1s-> 3s)

The default tcp connection and tls handshake timeout all has been relaxed to 5 seconds default in recent releases. You would get the relaxed timeout from 3.0.0-beta.2 and later versions.

**Comment by klim-iv** [comment]
> > Thanks, I'll try, but maybe better to little bit increase connect-timeout in default values? (1s-> 3s)
> 
> The default tcp connection and tls handshake timeout all has been relaxed to 5 seconds default in recent releases. You would get the relaxed timeout from 3.0.0-beta.2 and later versions.

Oh, I see - fresh commit :-)
Thank you!

**Pull request closed without merging**
