### PR TITLE
Add support for all the IANA registered HTTP methods

### PR DESCRIPTION
**Pull request by alexandrebouthinon**
## PR Type

Feature

## PR Checklist

- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

This PR add support for all the IANA RFCs described HTTP verbs except `MOVE` and `*` because they're rust keywords (if you know a trick to get around the problem and thus complete the list, I am interested 🙂).
See the complete list on the [IANA website](https://www.iana.org/assignments/http-methods/http-methods.xhtml#methods)

### CODE REVIEW

**Comment by ibraheemdev** [comment]
Can we not just support any string literal? I don't see the point of restricting it if we're already accepting non-standard methods.. other than not catching typos.

**Comment by robjtede** [comment]
related to #2893

**Comment by alexandrebouthinon** [comment]
> Can we not just support any string literal? I don't see the point of restricting it if we're already accepting non-standard methods.. other than not catching typos.

If you want I can close this one and make a new one to manage a custom string. But I don't know if Andrew is still working on it

**Comment by alexandrebouthinon** [comment]
I've been thinking about this and my opinion is that the request of custom literals support for HTTP methods in a framework is almost always motivated by the need to use one or more of the additional methods described by IANA. 

  Moreover, I have looked a bit and I think that adding this support will increase drastically the complexity and the difficulty of maintaining the project (especially without wanting to release a new major version and therefore making design concessions during implementation) 😅 

What do you think?

**Comment by JohnTitor** [comment]
Because we use the http crate for HTTP methods in some places, I think it makes some sense to keep consistency with [their methods list](https://docs.rs/http/latest/http/method/struct.Method.html) to simplify handling, and accepting other methods as user-defined sounds better to me.
Also, modifying only `method_type!` inputs adds partial support, not full support, right? Then, uhm, I guess it'd also add a certain complexity.

**Comment by alexandrebouthinon** [comment]
> Because we use the http crate for HTTP methods in some places, I think it makes some sense to keep consistency with [their methods list](https://docs.rs/http/latest/http/method/struct.Method.html) to simplify handling, and accepting other methods as user-defined sounds better to me. Also, modifying only `method_type!` inputs adds partial support, not full support, right? Then, uhm, I guess it'd also add a certain complexity.

That's right, so I'm going to close this PR and work on the string literals support. Thank you for taking time to follow up my questions 🙂

**Pull request closed without merging**
