### PR TITLE
Actix-multipart - Remove unwraps

### PR DESCRIPTION
**Pull request by ghost**
## PR Type

Bug Fix

## PR Checklist

- [ ] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] A changelog entry has been made for the appropriate packages.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

Remove unwrap where not necessary for actix multipart.

### CODE REVIEW

**Comment by robjtede** [comment]
In what scenario have you observed these panic?

**Comment by ghost** [comment]
Hi ! I did observed these panic when building a simple http server with multipart. 
I did extend the `FieldReader` trait and called `try_next()` from `futures_util::stream::try_stream::TryStreamExt` on `field`. This caused the panics.

**Comment by robjtede** [comment]
I'd like to see tests added that trigger this panic without the patch, please.

**Comment by robjtede** [comment]
Had some time to work on a reproduction of this panic in #3397. I think it's correct to use [.fuse()](https://docs.rs/futures-util/latest/futures_util/stream/trait.StreamExt.html#method.fuse) on the `Field` in your custom `FieldReader` impl to prevent the panic.

**Comment by rlebran** [comment]
Hi, I didn't had time nor managed to work on a reproduction (+ I deleted the repository when migrating my github account). 
Thank you for finding the time to explore and for your response !

**Pull request closed without merging**
