### PR TITLE
add FromParam for bool

### PR DESCRIPTION
**Pull request by mwarning**
Allow false/true as url parameter:
```
let is_valid : bool = req.match_info().query("is_valid");
```

### CODE REVIEW

**Comment by DoumanAsh** [comment]
@mwarning Could you please add simple test to check its usage?

**Comment by mwarning** [comment]
hm, I do not know how. This did not compile:
```
assert_eq!(
  Params::with_url(&Url::new("/foo/bar?value=true".parse::<http::Uri>().unwrap())).query("value"),
  Ok(true)
);
```

**Comment by DoumanAsh** [comment]
See example of tests in the same file https://github.com/actix/actix-web/blob/master/src/param.rs#L274-L277

**Comment by DoumanAsh** [comment]
Well it is not necessary now I think about it.
Can you please rebase your changes

**Review by DoumanAsh — APPROVED** [review]

**Review by DoumanAsh — CHANGES_REQUESTED** [review]
I remembered one thing. In past we had similar PR but Nikolay decided against it.
https://github.com/actix/actix-web/pull/360

@fafhrd91 Are you still of the same opinion?

**Comment by mwarning** [comment]
I use a GET request to call a method that accepts a bool as parameter. That is why I like to parse a bool.
Right now I have a workaround:
```
let info = req.match_info();
if let (Ok(count), Ok(closed)) = (info.query("count"), info.query("closed")) {
  let closed : u32 = closed;
  add_line(count, closed != 0);
}
```

**Comment by fafhrd91** [comment]
Path extractor seems easier. In you css you can just do

`let data = Path::<(u32, bool)>::extract(&request)`

And if you use handler with extractor it is even easier

`fn index(data: Path<(u32, bool)>) -> HttpResponse `

**Comment by DoumanAsh** [comment]
@fafhrd91 emm so I'm not sure do you mean this PR is not necessary or...?

**Comment by fafhrd91** [comment]
I’d prefer to kill FromParam

**Comment by mwarning** [comment]
@fafhrd91 I do not see how I can apply `extract` to my problem. Does this parse `foo.bar?123&true`?

**Comment by fafhrd91** [comment]
match_info does not contain query, only patch match information. Query is extractor for req query

**Comment by mwarning** [comment]
I can't use a path, this might conflict with existing files.
This might might be a way to get what I need: https://github.com/actix/actix-web/blob/master/src/extractor.rs#L962
But writing a struct seems to be a bit of a hassle. Also, how do I import the Deserialize macro?

**Comment by fafhrd91** [comment]
example with count and closed

```rust
#[derive(Deserialize)]
struct Params {
    count: u32,
    closed: bool,
}
```

and use it like this:

```rust
fn index(params: Query<Params>) -> HttpResponse {
   params.count, params.closed
}
```

**Comment by fafhrd91** [comment]
i will remove FromParams trait in 0.8

**Comment by mwarning** [comment]
ok

I need to match `index.html?count=42&close=true`, but this did not seem to match:
```
if let Ok(p) = Query::<Params>::from_request(&req, &()) {
	println!("count: {}, close: {}", p.count, p.close);
}
```

**Comment by fafhrd91** [comment]
it should, you need to enable logging. also in my example i use `closed`.

https://actix.rs/actix-web/actix_web/struct.Query.html

**Comment by mwarning** [comment]
This is more of my code:
```
#[derive(Deserialize)]
struct Params {
	count: u32,
	close: bool,
}

fn web_handler(req: &HttpRequest) -> HttpResponse {
  if *req.method() != http::Method::GET {
    return HttpResponse::MethodNotAllowed().finish();
  }

  println!("{:?}", req.query()); // prints: {"uid": "1537985931152", "close": "0", "count": "3"}

  if let Ok(p) = Query::<Params>::from_request(&req, &()) {
    println!("count: {}, close: {}", p.count, p.close);
  }
  return HttpResponse::Ok().finish();
}
```
Hm, maybe I have to also parse&ignore that uid my browser is sending.. EDIT: nope, that did not change. The order also does not seem to be important. actix-web 0.7.7

**Comment by fafhrd91** [comment]
What error do you get? Also try to change `close` to `usize`

**Comment by mwarning** [comment]
I changed close to usize and that fixed the problem. Thanks a lot!

**Comment by mwarning** [comment]
Sorry for asking here, what kind of query does `Query::<(String, String)>::from_request(&req, &())` match?
(is there some chat that does not require a login?)

**Comment by fafhrd91** [comment]
I don’t think you can do (String, String) for query

**Pull request closed without merging**
