### PR TITLE
prepare releases: actix-http 3.0.0 and actix-web 4.0.0

### PR DESCRIPTION
**Pull request by robjtede**
## PR Type

Release

### Notes
Further crate releases will follow in the coming couple days without PRs.

### CODE REVIEW

**Review by Dowwie — APPROVED** [review]
v4 is ready!

**Review by JohnTitor — APPROVED** [review]
Thanks for making v4 real!

**Comment by moy2010** [comment]
Yay! Time to upgrade :rocket:

**Comment by rahuahua** [comment]
finally!!!! bravo~

**Review by aliemjay — APPROVED** [review]
:+1:

**Pull request merged**
