### PR TITLE
add rustls support for actix-http and awc

### PR DESCRIPTION
**Pull request by jeizsm**

### CODE REVIEW

**Comment by DavidBM** [comment]
Really looking forward to this pull request.

**Comment by fafhrd91** [comment]
Could you add tests and entry to changes to both crates. Otherwise looks good

**Comment by fafhrd91** [comment]
actix-connect 0.2.2 is released

**Comment by fafhrd91** [comment]
Why did you switch to 0.3?

**Comment by jeizsm** [comment]
I switched it to 0.3 because of breaking change in `ssl` function in connector.  But it broke error compability with actix

**Comment by fafhrd91** [comment]
0.3 is not good idea. lets leave ssl function as is just add new one `fn rustls(..)` internally you can use your SslConnector struct

**Comment by jeizsm** [comment]
Done

**Comment by fafhrd91** [comment]
looks good. but could you move test-server changes to separate PR and same for Cargo.toml changes

**Comment by jeizsm** [comment]
I removed Cargo.toml changes in all projects and rustls support in test-server, but I need all other changes in test-server. Or you meant move to another PR extracting ssl tests from test_server?

**Comment by fafhrd91** [comment]
do you need test-server changes for this PR?

**Comment by jeizsm** [comment]
Yes, rustls_server tests fail without it

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
thanks!

**Comment by fafhrd91** [comment]
@jeizsm btw would you like to join contributors team?

**Comment by jeizsm** [comment]
@fafhrd91 Yes, I would like to participate

**Pull request merged**
