### PR TITLE
Add protobuf support

### PR DESCRIPTION
**Pull request by kingxsp**
add google protobuf support.

### CODE REVIEW

**Comment by fafhrd91** [comment]
that is pretty cool!

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
oh, I merged it too fast :)

could you add some tests

**Comment by messense** [comment]
I think this should be feature gated and off by default to avoid pulling in too many dependencies?

**Comment by fafhrd91** [comment]
i agree, i will add feature later

**Comment by kingxsp** [comment]
@fafhrd91  ok! I will write test in protobuf.rs.  protobuf-example run is ok！

**Comment by fafhrd91** [comment]
It is more about make sure everything will work in future

**Comment by fafhrd91** [comment]
after careful consideration of all implications of protobuf code, i decided to move it to example.
i am definitely interested in proper protobuf integration, but this needs more thinking. also i think protobuf code belongs to separate library, something like actix-protobuf

**Comment by kingxsp** [comment]
I waiting for actix-protobuf. I hope to come soon.

**Comment by fafhrd91** [comment]
@kingxsp I don't have much time at the moment but I can create repo and give you write access. what do you think?

**Comment by kingxsp** [comment]
@fafhrd91 ok! let me try. Before this, do you have any ideas or suggestions? I think the current example of protobuf.rs is good, move this file to the new repo and add the test and example is done.

**Comment by fafhrd91** [comment]
@kingxsp I added repo for you, you need to accept invitation

**Pull request merged**
