### PR TITLE
Convert from `derive_more` to `thiserror`

### PR DESCRIPTION
**Pull request by otavio**
The thiserror has the advantage of implementing std::error::Error and it
integrates better with the Rust ecosystem.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by otavio** [comment]
This does the change for the `http` crate but I can continue converting more crates if desired. Please give me the project view of the project on this.

**Comment by JohnTitor** [comment]
At a glance, I'm fine with that since we shouldn't lose anything and can reduce dependencies size. But let's hear other thoughts from contributors.

**Comment by JohnTitor** [comment]
Also it'd be great if you could resolve conflict with rebase.

**Comment by otavio** [comment]
> Also it'd be great if you could resolve conflict with rebase.

Sure, just did it. Thanks for looking at it @JohnTitor

**Comment by otavio** [comment]
The _CI Windows_ failure seems to be not related.

**Comment by Dowwie** [comment]
Seems like a net gain for the ecosystem.  Actix error compatibility could use improving.  I think that this needs regression testing and feedback, just to be sure.

@mitsuhiko  as a resident expert about error handling, what do you think?

**Comment by bitemyapp** [comment]
`thiserror` has seemed pretty unobtrusive by design from my use of it. I use `anyhow` and `thiserror` in my projects. I'd be in favor but I'll defer to someone with more experience and expertise, such as @mitsuhiko.

**Comment by tyranron** [comment]
Error deriving in `derive_more` is about to be landed, so I'm unsure whether this change is meaningful. Some tips in favor of `derive_more`:
- Supports more `std` traits. `derive(From)` is used quite oftenly in my practice. Stuff [like this](https://github.com/actix/actix-web/blob/1fa02b5f1c331f26f188627effd0b8af8a675893/actix-http/src/header/shared/httpdate.rs#L35-L39) could be replaced with a single attribute making the codebase cleaner.
- Clever [about generics](https://github.com/JelteF/derive_more/blob/master/tests/display.rs#L210-L212).
- Won't impose problems in integration with `anyhow` as the latest integrates well with any `Error`s.

As for dependencies: both `thiserror` and `derive_more` use only `proc-macro2`, `syn` and `quote`, so there is no actual dependencies reduce.

**Comment by otavio** [comment]
> Error deriving in `derive_more` is about to be landed, so I'm unsure whether this change is meaningful. 

I am fine either way. Considering `derive_more` adds it, it makes sense to keep using it as it can reduce even more core.

If everyone agrees, once `derive_more` is released, I can rework this PR.

**Comment by robjtede** [comment]
> As for dependencies: both thiserror and derive_more use only proc-macro2, syn and quote, so there is no actual dependencies reduce.

I think this is what kills this PR for me.

If we can wait a small while and add the better error deriving with sources/backtraces using derive_more, I'm in favor of that.

**Comment by JohnTitor** [comment]
> As for dependencies: both thiserror and derive_more use only proc-macro2, syn and quote, so there is no actual dependencies reduce.

Ohhh, somehow I was confused, perhaps saw other crate page :P

**Comment by otavio** [comment]
We will be waiting for `derive_more` to finish adding `Error` support, so this PR should be closed.

In meanwhile I made #1422 to allow the `Error` use for more types.

**Comment by Dowwie** [comment]
derive_more 0.99.5 just released, featuring std::Error support

thanks @tyranron  !

**Pull request closed without merging**
