### PR TITLE
Expose the max limit for payload sizes in Websocket Actors. #925

### PR DESCRIPTION
**Pull request by anthonyjchriste**
This PR exposes the ability to set a max size limit for Websocket payloads when creating a Websocket actor.

This is a PR for #925 

I added the following new public API methods:
* ws - `start_with_limit<A, T>(actor: A, req: &HttpRequest, stream: T, limit: usize) -> Result<HttpResponse, Error>`
* WebsocketContext - `start_with_limit<A, T>(actor: A, req: &HttpRequest, stream: T, limit: usize) -> Result<HttpResponse, Error>`
* WebsocketContext - `pub fn with_factory_codec<S, F>(
        stream: S,
        f: F,
        limit: usize,
    ) -> impl Stream<Item = Bytes, Error = Error>`

and modified the following private API methods:
* WebsocketContextFut - `fn new(ctx: WebsocketContext<A>, act: A, mailbox: Mailbox<A>, limit: usize)`
* WsStream - `fn new(stream: S, limit: usize) -> Self `

I played around with the idea of changing ws::start to be `pub fn start<A, T>(actor: A, req: &HttpRequest, stream: T, limit: Option<usize>) -> Result<HttpResponse, Error>`, but I didn't want to break the public API.

I'm not a master of API design, so any feedback would be appreciated.

### CODE REVIEW

**Review by fafhrd91 — CHANGES_REQUESTED** [review]
let's add just one method `WebsocketContext::with_codec()`, if you need custom codec it should be fine to implement custom start function. also do not include formatting in pr or rust `cargo fmt`

**Comment by anthonyjchriste** [comment]
Thank you for the feedback. It is very much appreciated.

I created a single WebsocketContext::with_codec method and modified the private interfaces for creation of WsStreams and WebsocketContextFut to accept a codec during creation. Please let me know if you would prefer separate with_codec methods on those structs as well. I also had to make Codec Copy/Clone so that it could be passed to both the WsStream and WebsocketContextFut structs. 

I also did not touch the version numbers in the actix-web-actors or actix-http crates. I wasn't sure if that was something you wanted me to do or something you should handle.

I also reverted the formatting that IntelliJ added. Thank you for the time in reviewing these PRs. 

I apologize if advance if I'm messing up the pull request process. This is my first time attempting to submit a PR to an opensource project so your patience and guidance is appreciated.

**Comment by anthonyjchriste** [comment]
So to get the patched version working in my project, I had to bump the patch number and update the cargo files for actix-web, actix-http, and actix-web-actors. I'm not sure if that is the correct course or not. If you want those changes, let me know I and will commit them.

**Comment by anthonyjchriste** [comment]
Just an FYI, I'm going to be on vacation until mid-July. I look forward to working with you to get this merged when I get back.

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
thanks!

**Comment by igorhoogerwoord** [comment]
The method "start_with_limit" seems to be removed again in 3.0 -> was there a reason for it, or is it available somewhere else?

**Pull request merged**
