### PR TITLE
doc: Add example for using custom nativetls connector

### PR DESCRIPTION
**Pull request by untitaker**
follow-up to #491

### CODE REVIEW

**Comment by untitaker** [comment]
I promised to add this but forgot

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
thanks!

**Comment by DoumanAsh** [comment]
@untitaker can you please rebase?

**Comment by untitaker** [comment]
@DoumanAsh hope you don't mind, did it via the github web UI

**Comment by untitaker** [comment]
I can't tell why the appveyor build fails

**Comment by DoumanAsh** [comment]
@untitaker I guess it is weather 😄

**Review by DoumanAsh — APPROVED** [review]

**Pull request merged**
