### PR TITLE
Refactored macros

### PR DESCRIPTION
**Pull request by olegnn**

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]

**Comment by robjtede** [comment]
Not familiar enough with macros to review this, anyone else @actix/contributors wanna look this over?

**Comment by cetra3** [comment]
@olegnn Can you confirm if you're having an issue with the current implementation? Or is this just a cleanup?

**Comment by olegnn** [comment]
@cetra3 just a cleanup.

**Review by JohnTitor — APPROVED** [review]
Sorry for the delay! There was a flood of notifications :/

**Comment by pickfire** [comment]
@JohnTitor Is https://github.com/olegnn/actix-web/pull/1 good?

**Comment by JohnTitor** [comment]
@pickfire Looks good! Feel free to send a PR to upstream :)

**Pull request merged**
