### PR TITLE
Replace unsafe content length helper

### PR DESCRIPTION
**Pull request by robjtede**
Tackling the low-hanging fruit. Attempting to replace unsafe blocks in the actix-http h1 helpers.rs file with safe equivalents that are as performant as possible (though I don't expect a small decrease in the performance of these functions to materially impact an overall request's performance).

### CODE REVIEW

**Review by cdbattags — DISMISSED** [review]

**Comment by robjtede** [comment]
@cdbattags not done yet, my dude :)

**Comment by cdbattags** [comment]
> @cdbattags not done yet, my dude :)

Yezzir, sorry I didn't know we're gating PRs around approvals now. My culture for approvals usually stems as just "I'm good with your current approach" instead of a "this immutable chunk of changes is good to go" if that makes sense.

Obviously saw the draft as well.

**Comment by robjtede** [comment]
Ready for review.

Here's the violin plot from the benchmark run. Currently the fast path covers responses <10Kb. We could easily add another case for <100Kb if desired.

safe

**Comment by JohnTitor** [comment]
Looks good to me!

> We could easily add another case for <100Kb if desired.

Yeah, let's add it.

**Comment by robjtede** [comment]
There are now fast paths for responses up to 1MB.

2020-02-24_20 54 56-8de68e0a

**Review by JohnTitor — APPROVED** [review]

**Pull request merged**
