### PR TITLE
Improve documentation for FromRequest::Future

### PR DESCRIPTION
**Pull request by mattfbacon**
## PR Type

Other: Documentation

## PR Checklist

- [N/A] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [N/A] A changelog entry has been made for the appropriate packages.
- [X] Format code with the latest stable rustfmt.
- [N/A] (Team) Label with affected crates and semver status.

## Overview

Improve documentation for the `Future` associated type of the `FromRequest` trait. I was confused by this and made [a Rust forum post](https://users.rust-lang.org/t/actix-web-fromrequest-where-future-ready/74280/3) where I got some help so I thought it would make sense to add this to the documentation.

No breaking changes.

### CODE REVIEW

**Comment by robjtede** [comment]
The best practice for Actix Web is to use `LocalBoxFuture` instead. I'd also prefer not to mention nightly features in our docs for now.

**Comment by mattfbacon** [comment]
> The best practice for Actix Web is to use `LocalBoxFuture` instead. I'd also prefer not to mention nightly features in our docs for now.

OK

**Comment by fakeshadow** [comment]
You can also make a new type and implement `Future` trait and `LocalBoxFuture` is just an alias for `Pin<Box<dyn Future>>`  .The doc of actix-web should not try to offer a hand holding tutorial on basic language feature. It can get outdated easily(async Rust is still in development) and it can't do a good job on explaining it thoroughly.

**Comment by mattfbacon** [comment]
I tried to find resources on this information and couldn't find any. And even when I asked on the forum, a Rust (specifically async; Alice is a primary maintainer of Tokio) expert said something different than what you all are saying. So it's not true that it's a "basic language feature" (it's not a language feature at all, but that's beside the point).

Anyway, I think it would be helpful. There are no examples that I could find in the docs that used it.

**Comment by mattfbacon** [comment]
Sorry, part of my previous comment was incorrect. I found one example using LocalBoxFuture in one place. :smiley:

**Comment by fakeshadow** [comment]
I'm not saying the language feature have a good discovery. I'm saying said discovery does not belong to actix-web library. Making related question more easy to get answer of from other source is better than burden some library that not maintained by rust-lang domain.
With major improvement of async Rust language feature someone have to keep the information updated and who would do that for actix-web?

**Comment by fakeshadow** [comment]
BTW `async-trait`'s readme have a detailed explain for this issue https://github.com/dtolnay/async-trait

**Comment by mattfbacon** [comment]
>  I'm saying said discovery does not belong to actix-web library

The existence of boxed futures, no, but the Actix convention to use LocolBoxFuture yes.

> With major improvement of async Rust language feature someone have to keep the information updated

If the convention changes from LocalBoxFuture to something else (maybe `impl Future` once that stabilizes), that should be documented.

>  who would do that for actix-web?

Whoever created and/or will change the convention.

**Review by robjtede — APPROVED** [review]

**Pull request merged**
