### PR TITLE
Implement failure::Fail for actix_web::Error.

### PR DESCRIPTION
**Pull request by marmistrz**
This is done in order to allow using actix_web::Error with crates such as failure.

As of `actix-web` 0.7.18 is it impossible to return `failure::Error` from functions using `actix-web` internally:
```
    let mut sys = System::new("test");
    let fut = get_future();
    sys.block_on(fut).map(|e| e.into())
```
which fails with
```
269 |     sys.block_on(fut).map_err(|e| e.into()) //.map_err(|e| format_err!("{}", e))
    |                                     ^^^^ the trait `std::error::Error` is not implemented for `actix_web::error::Error`

```

### CODE REVIEW

**Comment by fafhrd91** [comment]
could you add test

**Comment by mehcode** [comment]
This would be massively awesome. Currently my integration tests return `actix_web::Result` and have to `unwrap` non client request errors.

**Comment by marmistrz** [comment]
I've rethought this change and we definitely don't want to just `impl std::error::Error` - we'll just throw away all the context information.

I've just properly implemented `failure::Fail` for `actix_web::Error` and this should do the trick. Probably the test should rather be a doc-test, but I'm not sure how to rewrite it so that it's suited for doc.

**Comment by mehcode** [comment]
@marmistrz This PR removes `as_fail` and `cause`. Can those be put back in so this won't be a breaking change?

**Comment by marmistrz** [comment]
> @marmistrz This PR removes as_fail and cause. Can those be put back in so this won't be a breaking change?

@mehcode They should be implemented automatically, IIRC. You may need to import some traits though. I'll recheck tomorrow

**Comment by mehcode** [comment]
@marmistrz Still makes it a breaking change as libraries ( such as sentry-actix ) are depending on them being inherent methods.

**Comment by marmistrz** [comment]
@mehcode this change has to be breaking, because to properly implement `Fail` we need to return `Option<&Backtrace>` and not `&Backtrace` as actix-web currently does it. 

I'd like to hear what the opinion of the maintainers is, though.

**Comment by fafhrd91** [comment]
just fyi, I am dropping failure in 0.8, failure will be supported but actin_web::Error won't be based on Fail anymore.

**Comment by fafhrd91** [comment]
@marmistrz could you re-evaluate this PR for 1.0? 1.0 is in master now

**Comment by marmistrz** [comment]
Ok. I'll try migrating my code to 1.0 and see if things work as expected or if there are any changes needed.

**Comment by marmistrz** [comment]
This PR still looks relevant, because even though current master drops the `failure` crate, the error types still don't seem to implement `std::error::Error`. I'll wait with updating the PR to target 1.0 until the migration guide is ready.

**Comment by fafhrd91** [comment]
@marmistrz could you update it then. but i dont want to enforce `Error` trait on `ResponseError`

**Comment by marmistrz** [comment]
Ok, so I'll wait until I can port my app to 1.0 and then see which types actually need the implementation of `std::error::Error`.

May I ask why you don't want `std::error::Error` for `ResponseError`?

**Comment by fafhrd91** [comment]
`std::error::Error` adds a lot of boilerplate code. ie i usually just create error enum, something like

```rust
#[derive(From, Display)]
enum MyError {
  Err1,
  Err2,
  Err3(OtherError),
}
```

and `Error` trait would cause a lot of boilerplate unless we introduce some derive macro. i use derive_more extensively for `From` and `Display` macros

**Comment by DoumanAsh** [comment]
@fafhrd91 Current `Error` is cheap because it depends on `Display` now. i.e. it requires no implementation since it uses `Display` to show error
But yeah, I think there is no need to require `std::error::Error` since it serves a little purpose, but we can make our own errors to impl the `Error` trait

**Comment by fafhrd91** [comment]
yes, `actix_http::Error` can implement `std::Error`

**Comment by fafhrd91** [comment]
`std::error::Error` impl added to `Error`. It is not possible to implement `Fail` for Error because failure requires `Send + Sync` for errors

**Pull request closed without merging**
