### PR TITLE
Update TechEmpower benchmarks to round 16

### PR DESCRIPTION
**Pull request by memoryruins**
Well done :)

### CODE REVIEW

**Comment by fafhrd91** [comment]
thanks!

**Comment by pickfire** [comment]
Now there is techempower benchmark round 17 but the performance drop slightly, should we update it?

But somehow actix-raw in data-updates section are way faster than the others.

**Comment by fafhrd91** [comment]
Yes, we can update. Db benchmarks are better because now they use async pg driver

**Comment by pickfire** [comment]
@fafhrd91 Nice, now it seems that db are way faster than the others. Do you know what is the reason on the minor performance drop on plain text benchmark?

**Comment by fafhrd91** [comment]
who knows, maybe power fluctuation or solar flare, or may someone stepped on network cord

**Pull request merged**
