### PR TITLE
impl downcast_ref for MessageBody

### PR DESCRIPTION
**Pull request by leptonyu**
#1286

### CODE REVIEW

**Review by cetra3 — APPROVED** [review]
This pattern is already used within [error](https://github.com/actix/actix-web/blob/1d12ba9d5ff691178c3fe61f3f662ca7d98080d2/actix-http/src/error.rs#L97), it is a cut & paste of the code basically so I don't see an issue with it

**Review by zzy — APPROVED** [review]

**Comment by Dowwie** [comment]
This feels regressive.  Should anyone approve adding unsafe to this code base, even if prior work exists?  I'm not suggesting this work be rejected but rather the original unsafe and this one both refactor away the need for unsafe.

@actix/contributors Stop all new unsafe, regardless of precedent

**Comment by mitsuhiko** [comment]
I think this generally makes sense. I would propose hiding this behind a macro so we can reuse the code safely in more than one place. There is no way to implement this without unsafe and neither std::error/any/failure/error or anything else does anything different here.

**Comment by Dowwie** [comment]
@leptonyu if this PR is to move forward, it requires wrapping the relevant unsafe in a macro and using that macro where applicable

**Comment by leptonyu** [comment]
@Dowwie ok, I need sometime to do it.

**Comment by leptonyu** [comment]
@robjtede I've updated the code.

**Comment by robjtede** [comment]
LGTM.

Ping @cetra3 @zzy

**Comment by cetra3** [comment]
LGTM

**Review by zzy — APPROVED** [review]

**Comment by JohnTitor** [comment]
Sorry for the delay! My bandwidth is quite tight now :/
I'm fine with this, any concerns? @actix/contributors also cc @Aaron1011 

@leptonyu btw, could you please stop requesting review frequently? We'll review PRs with our free time :)

**Review by robjtede — APPROVED** [review]

**Review by Aaron1011 — APPROVED** [review]

**Comment by leptonyu** [comment]
@JohnTitor ok

**Review by JohnTitor — APPROVED** [review]

**Comment by JohnTitor** [comment]
Thanks!

**Pull request merged**
