### PR TITLE
Use old clippy attributes syntax

### LINKED ISSUE #561: Unable to use stable clippy with actix-web
`clippy::lint_name` syntax is experimental, so it is impossible to use stable clippy if `actix-web` is a dependency.

### PR DESCRIPTION
**Pull request by stanislav-tkach**
As far as I can see, "old" syntax works both with nightly and stable clippy.

Closes #561.

### CODE REVIEW

**Comment by DoumanAsh** [comment]
@fafhrd91 I don't use clippy at all, is it fine to update?

**Comment by mehcode** [comment]
The new syntax is stable in 1.30 which was released today.

**Comment by stanislav-tkach** [comment]
@mehcode Unfortunately, it isn't that simple:
```
$ rustc --version
rustc 1.30.0 (da5f414c2 2018-10-24)
$ rustup --version
rustup 1.14.0 (1e51b07cc 2018-10-04)
$ cargo --version
cargo 1.30.0 (36d96825d 2018-10-24)
...
error[E0658]: scoped lint `clippy::needless_pass_by_value` is experimental (see issue #44690)
```
https://travis-ci.com/exonum/exonum/jobs/154392451#L2159

**Comment by mehcode** [comment]
Ah. I was confused because of https://github.com/rust-lang/rust/issues/55331

Seems it won't be stable until 1.31

**Review by DoumanAsh — APPROVED** [review]

**Comment by DoumanAsh** [comment]
@fafhrd91 I merged since old syntax should work with both versios

**Pull request merged**
