### PR TITLE
feature: allow TestServer to open a websocket on any URL

### LINKED ISSUE #432: No way to specify a socket URI for TestServer.ws()
It appears that in `test.rs`:

```rust 
pub fn ws(
        &mut self,
    ) -> Result<(ws::ClientReader, ws::ClientWriter), ws::ClientError> {
        let url = self.url("/");
        self.rt
            .block_on(ws::Client::with_connector(url, self.conn.clone()).connect())
}
```
`url` is hard set to "/". 
I have several entry points for websockets for my app, and I would like to be able to specify the path. The app allows for this, but unfortunately, testing does not.

I'm not sure what the preferred approach might be, possibly a second fn that takes a path string?

Thanks!

### PR DESCRIPTION
**Pull request by jrconlin**
* added `TestServer::ws_at(uri_str)`
* modified `TestServer::ws()` to call `self.ws_at("/")` to preserve
behavior

Closes #432

### CODE REVIEW

**Comment by fafhrd91** [comment]
Looks good. Could you add test case and entry to changes.md

**Review by fafhrd91 — APPROVED** [review]

**Comment by jrconlin** [comment]
Sure thing. Granted, I kinda figured that the test case for `ws()` should cover it, since it falls through to `ws_at("/")`, but I can create an explicit one.

**Comment by fafhrd91** [comment]
Yes, I’d like to have explicit test case.

**Comment by jrconlin** [comment]
By the way, we've been using [clog](https://github.com/clog-tool/clog-cli) as part of our release process. It automatically updates the CHANGES.md file from the submitted PRs, although it does require patch authors to properly tag their patches, but it's fairly straight forward. (Here's [an example](https://github.com/mozilla-services/autopush-rs/blob/master/CHANGELOG.md) of clog output.)

Not sure if it might help, but figured it might be useful.

**Comment by fafhrd91** [comment]
thanks! I'll add test

**Comment by fafhrd91** [comment]
oh! you added test, thanks

**Pull request merged**
