### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by Gumichocopengin8**
## PR Type

Refactor

## PR Checklist

- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview
I fixed some warnings that `cargo clippy` generated.

### CODE REVIEW

**Comment by Gumichocopengin8** [comment]
@robjtede could you run ci tests for me? Thanks

**Comment by Gumichocopengin8** [comment]
Clippy also says
```
src/server.rs#L31
field is never read: `client_shutdown`
```
but I'm not sure I can actually remove `client_shutdown`. Is it saved for future use?

**Comment by fakeshadow** [comment]
> but I'm not sure I can actually remove `client_shutdown`. Is it saved for future use?

https://github.com/actix/actix-web/issues/2091

**Comment by Gumichocopengin8** [comment]
@robjtede could you run ci tests again? Thanks.
The CI is not working for the first-time contribution btw?

**Pull request merged**
