### PR TITLE
properly drop h2 connection

### LINKED ISSUE #1123: actix-client doesn't close HTTP2 connection when run out of conn_lifetime
It happens in our staging server. A minimum example to reproduce:

Dependency:
```toml
[dependencies]
actix = "0.8.3"
actix-web = { version = "1.0", features = ["ssl"] }
futures = "0.1"
tokio-timer = "0.2"
serde_json = "*"
serde = "*"
```

main.rs:
```rust
use actix::System;
use actix_web::client::{Client, Connector};
use futures::future::{lazy, Future};
use std::time::Duration;
const CONNECT_TIMEOUT: Duration = Duration::from_secs(10);
use futures::stream::Stream;
use tokio_timer::Interval;

#[macro_use]
extern crate serde_json;

fn main() {
    let client = Client::build()
        .timeout(CONNECT_TIMEOUT)
        .connector(
            Connector::new()
                .conn_lifetime(Duration::from_secs(2))
                .conn_keep_alive(Duration::from_secs(1))
                .finish(),
        )
        .finish();
    System::new("test")
        .block_on(lazy(|| {
            Interval::new_interval(Duration::from_millis(100))
                .map_err(|e| println!("{}", e))
                .for_each(|_| {
                    client
                        .post("https://explorer.nearprotocol.com/api/node")
                        .header("Content-Type", "application/json")
                        .send_json(&json!("aaa"))
                        .map_err(|_| ())
                        .map(|_| ())
                })
                .map(|_| ())
        }))
        .unwrap();
}
```

```sh
cargo build
target/debug/actix-test # assume project name is actix-test
ps aux | grep actix-test # get pid
watch 'lsof -i -a -p <pid>'
```

You will see unclosed connection is growing every 2s.

I found this only happens when server is http/2, and did some basic debugging. My finding: in actix-http/src/client/pool.rs, it only closes connection when connection type is http1, and http2 case was not handled.

### PR DESCRIPTION
**Pull request by fakeshadow**
## PR Type

Bug Fix

## PR Checklist

- [x] Documentation comments have been added / updated.
- [x] Format code with the latest stable rustfmt.
- [x] (Team) Label with affected crates and semver status.

## Overview

Wake up `h2::client::Connection` and resolve it's task when dropping `h2::client::SendRequest` 

 Closes https://github.com/actix/actix-web/issues/1123

### CODE REVIEW

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
Is there a sensible test case (even manual) for this or wsa fix verified using the code sample from the issue?

**Comment by fakeshadow** [comment]
> Is there a sensible test case (even manual) for this or wsa fix verified using the code sample from the issue?

I want to rework this use the join handle instead of a custom drop type with channel.
Test would be added with it

**Comment by fakeshadow** [comment]
@robjtede 
I notice join handle is not export in the current actix-rt  master branch use. So I add a test for manual drop and JoinHandle can be a future goal for refactor.

**Comment by robjtede** [comment]
huh? https://github.com/actix/actix-net/blob/master/actix-rt/src/lib.rs#L94

**Comment by fakeshadow** [comment]
> huh? https://github.com/actix/actix-net/blob/master/actix-rt/src/lib.rs#L94

Sorry my English is garbage. What I meant to say was actix-rt is pinned to `2.0.0-beta.2` in actix-web repo where JoinHandle is still not export yet.

**Review by robjtede — APPROVED** [review]
much cleaner with the join handle approach, nice job

**Pull request merged**
