### PR TITLE
fix guide examples code, rust not support '#' comment

### PR DESCRIPTION
**Pull request by ava57r**

### CODE REVIEW

**Comment by fafhrd91** [comment]
I don't think we should remove "# ", those are for reducing noise from examples.
all example get compiled in travis, ignore'ed examples won't compile.

**Comment by fafhrd91** [comment]
cargo doc and mdbook, both support "# "

**Comment by ava57r** [comment]
Did sample a few files.
Did it to check. In the examples looks unusual.

**Comment by fafhrd91** [comment]
"#" is usual for doc strings. as I said, "#" just hides noise from documentation

**Comment by xilec** [comment]
@fafhrd91, just compare rendered view [old](https://github.com/actix/actix-web/blob/master/guide/src/qs_2.md) and [new](https://github.com/andreevlex/actix-web/blob/9b79083b2647baa96831fd9bdcaec699b5c84c2f/guide/src/qs_2.md) variants.

**Comment by fafhrd91** [comment]
you should render guide with mdbook

https://actix.github.io/actix-web/guide/qs_2.html

**Comment by fafhrd91** [comment]
everything that is commented with "# ", is not relevant to documentation

for example:

```rust
# extern crate actix_web;
# use actix_web::*;
# fn index(req: HttpRequest) -> &'static str {
#    "Hello world!"
# }
# fn main() {
   Application::new()
       .resource("/", |r| r.f(index));
# }
```

in this example those lines exists only to satisfy compiler, and not relevant to documentation itself.
I like this comments because travis build compiles all examples and makes sure documentation is relevant.

**Comment by ava57r** [comment]
I realized a great thing, thanks for Your detailed and clear answer. I haven't written enough code infrastructure rust. Now it will use in its work.

**Comment by fafhrd91** [comment]
"cargo test --doc" supports "# "
to test docs or readme you can use https://crates.io/crates/skeptic

**Comment by fafhrd91** [comment]
actix-web build script with skeptic config https://github.com/actix/actix-web/blob/master/build.rs

**Pull request closed without merging**
