### PR TITLE
Add .remove() to response builder

### PR DESCRIPTION
**Pull request by kornelski**
Partial solution to #705

### CODE REVIEW

**Comment by DoumanAsh** [comment]
Why not to have `insert` method with similar semantics to `HeaderMap::insert`?

**Comment by kornelski** [comment]
That could be added as well. 

The builder has `set` and `header` taking headers in two different ways. Should there be two versions of insert too?

**Comment by DoumanAsh** [comment]
`set` is hidden for now, so I don't think we need to consider it as it is not part of public API let's say

**Comment by kornelski** [comment]
OK, added `insert` too

**Review by DoumanAsh — APPROVED** [review]

**Comment by DoumanAsh** [comment]
Thanks

**Comment by DoumanAsh** [comment]
P.s. Damn I forgot, I should update CHANGES.md

**Comment by fafhrd91** [comment]
@DoumanAsh could you check if we have same api in 1.0

**Comment by DoumanAsh** [comment]
@kornelski Could you please map the same method to response's builder in [actix-http](https://github.com/actix/actix-http) which will be used by actix-web 1.0

File `src/response.rs`

**Comment by kornelski** [comment]
actix-http is archived now, so I can't add this.

**Comment by fafhrd91** [comment]
actix-http is part of actix-web repo

**Pull request merged**
