### PR TITLE
Fix body propagation in Response::from_error.

### PR DESCRIPTION
**Pull request by boxdot**
Fix error body propagation in Response::from_error.

Also:

* Fix typos.
* Remove period from error messages.
* Add test for custom response in json error handler.

### CODE REVIEW

**Comment by fafhrd91** [comment]
I think with this change stops error message propagation

**Comment by boxdot** [comment]
> I think with this change stops error message propagation

I don't quite get it. `error_response` actually uses the response if it `InternalError::Response`.

Right now, it is not possible to return an error from a handler which will contain
some JSON information (or a different content type to text). Many APIs actually return a structured error message instead of plain text.

```
let mut buf = BytesMut::new();
let _ = write!(Writer(&mut buf), "{}", error);
resp.headers_mut()
    .insert(header::CONTENT_TYPE, HeaderValue::from_static("text/plain"));
resp.error = Some(error);
resp.set_body(Body::from(buf))
```

**Comment by Dokuro-YH** [comment]
I have encountered the same problem and my custom json error doesn't work.

**Comment by fafhrd91** [comment]
fixed in master

**Comment by boxdot** [comment]
It would have been possible to commit on top of my changes. But I guess whatever works. Thanks for merging.

**Pull request closed without merging**
