### PR TITLE
set the actix-web client send the http2 packet without ssl.

### PR DESCRIPTION
**Pull request by lgm-28**
I have created the interface to send http2 packets without ssl by following the method of sending http1.1 packets. And now I can send HTTP2 packets without ssl with use of set_http2() api.Do you guys think this is a feasible method? If not, can you tell me any good way to send HTTP2 packets without the SSL protocol. Thank you.

### CODE REVIEW

**Comment by fafhrd91** [comment]
does this code work? 

at the moment there is no way to use http2 over tcp connection.

**Comment by lgm-28** [comment]
Yes,I have made a test and it can work.

**Comment by fafhrd91** [comment]
I am not sure this can work. could you add test

**Comment by fafhrd91** [comment]
Reviewed again, this pr does not do what title says

**Comment by lgm-28** [comment]
OK， I will make a test and push again with new pull request if it works.

**Pull request closed without merging**
