### PR TITLE
update actix-http readme example.

### PR DESCRIPTION
**Pull request by fakeshadow**
## PR Type

Refactor

## PR Checklist

- [x] (Team) Label with affected crates and semver status.

## Overview

Update the readme example to show proper way of embedding `actix_web::App` into `actix-http`

### CODE REVIEW

**Review by robjtede — CHANGES_REQUESTED** [review]
think i'd prefer readme example be kept as pure actix-http and this be included in a new example

**Comment by fakeshadow** [comment]
All the questions I come across with have been asking how to use actix-http with actix-web.
This states a lot of what most users want from this crate.
The original example does not have any purpose and can be confusing of what it can do.

**Comment by robjtede** [comment]
> The original example does not have any purpose

Sure, but stating this crate as just another way to run -web apps is undervaluing it. We should be able to push it as a standalone thing.

**Comment by robjtede** [comment]
added in 9587261c2099ea46182147c7f8807f8b1055448e

**Pull request closed without merging**
