### PR TITLE
fix after update tokio-rustls

### PR DESCRIPTION
**Pull request by jeizsm**

### CODE REVIEW

**Review by DoumanAsh — APPROVED** [review]
looks good, thanks for noticing it

**Comment by DoumanAsh** [comment]
If you have time could you please add note to [changelog](https://github.com/actix/actix-web/blob/master/CHANGES.md) that `rustls` build is fixed?

**Comment by jeizsm** [comment]
@DoumanAsh done

**Comment by DoumanAsh** [comment]
Thank you,

@fafhrd91 could you please prepare new release for actix-web?
We currently can face compilation errors like https://travis-ci.org/actix/examples/jobs/439890976#L639

**Comment by fafhrd91** [comment]
We need test case

**Comment by DoumanAsh** [comment]
I added checks for individual TLS features to be sure that we verify each https://github.com/actix/actix-web/commit/d145136e569b49caec0fe87735ab0c736b2eb5de

**Pull request merged**
